### ISSUE TITLE
MSAL python 3 support ? 

### ISSUE THREAD

**Issue by bilalAchahbar** [AzureAD/microsoft-authentication-library-for-python#115]
I installed the current wheel library of msal from the official pypi reposirory.
But the wheel file has a python version of v2.
I try to install this library into my Azure Databricks Cluster where python 3 is configured. This conflicts because the wheel library of msal has python 2 configured. The library installed perfectly when I downgraded the cluster to python 2. But that can't be the solution because all my notebooks are programmed in python 3. I also can't think of any idea why the msal library isn't already in python 3 ?
Any workaround for this one.

**Comment by rayluo** [comment]
This is the first time we got this kind of report. Can you paste the error you encountered to let us know what exactly went wrong?

**Comment by bilalAchahbar** [comment]
I got this error inside my Azure Databricks cluster when I try to install the whl file from [this repo](https://pypi.org/project/msal/#files). This is **only when the python version is 3** when I downgrade my Azure databricks cluster to 2 and restart my cluster the library gets installed fine.
As you can understand python 2 is not the way of working for my cluster also because I wrote all my notebooks in 2 and I need version 3 on my clusters.

the reason I tried msal is because I read that adal is going to be deprecated, and that's why I tried msal to connect to my Azure resources from my Azure databricks notebooks.

```
java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, --upgrade, --find-links=/local_disk0/spark-28518881-6b4c-4f71-a879-22ce6689e6f5/userFiles-ef2c7c21-1e11-4869-bcfa-24d15fb07690, /local_disk0/spark-28518881-6b4c-4f71-a879-22ce6689e6f5/userFiles-ef2c7c21-1e11-4869-bcfa-24d15fb07690/msal-0.8.0-py2-none-any.whl, --disable-pip-version-check) exited with code 1. ERROR: msal-0.8.0-py2-none-any.whl is not a supported wheel on this platform.
 for library:PythonWhlId(dbfs:/FileStore/whl/msal-0.8.0-py2-none-any.whl,,NONE),isSharedLibrary=false
```

**Comment by lmazuel** [comment]
@rayluo you're missing a setup.cfg that says your wheel is universal. Hence Python 3 users ends up downloading the sdist and installing from source, which can be problematic. You can see on pypi your wheel is Python 2 only:
https://pypi.org/project/msal/#files

Just add a setup.cfg at the root like [this one](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/setup.cfg), et voila :)

**Comment by lmazuel** [comment]
By the way, you don't have to do a 0.8.1, just checkout the tag 0.8.0 and build the universal and upload it

**Comment by rayluo** [comment]
Thanks for @lmazuel 's helping hand! We've just manually [uploaded a universal wheel to PyPI](https://pypi.org/project/msal/#files). @bilalAchahbar please give `pip install msal` a try and let us know the result.

This issue will remain open, as we will also address it in our code base, and see how it works in the upcoming MSAL Python 0.9.0.
