### ISSUE TITLE
token cache: support logout

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-library-for-python#12]
The goal is to remove all tokens belong to a user name. In ADAL, with flat array, it is easy to do it through filtering by user_id; but now with the new universal token cache scheme, it is hard for client applications to do it.

**Comment by rayluo** [comment]
Indeed, with the new cache structure, it becomes unobvious to implement logout behavior. You won't believe how long we've been debating this internally. But now we will have a new PR to address this.
