### ISSUE TITLE
ConfidentialClientApplication is broken 0.8.0+

### ISSUE THREAD

**Issue by bobbrady** [AzureAD/microsoft-authentication-library-for-python#126]
The ConfidentialClientApplication function is broken with 0.8.0+.  

Steps to reproduce:
* Start with v0.7.0 working code from the samples [confidential_client_secret_sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_secret_sample.py)
* Upgrade to v1.0.0 `pip install msal`
* Run the sample again, get exception (see stacktrace below)
* Downgrade to v0.7.0, run sample, get token successfully

Tried and got same failure with every release version > 0.7.0

Stacktrace from simple wrapper around sample code
```
Traceback (most recent call last):
  File "graph_helper.py", line 111, in <module>
    my_graph_helper = GraphHelper()
  File "graph_helper.py", line 18, in __init__
    client_credential=self.config["GRAPH"]["CLIENT_SECRET"]
  File "/xxx/venv/lib/python3.7/site-packages/msal/application.py", line 143, in __init__
    validate_authority, verify=verify, proxies=proxies, timeout=timeout)
  File "/xxx/venv/lib/python3.7/site-packages/msal/authority.py", line 78, in __init__
    verify=verify, proxies=proxies, timeout=timeout)
  File "/xxx/venv/lib/python3.7/site-packages/msal/authority.py", line 127, in tenant_discovery
    payload = resp.json()
  File "xxx/venv/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rayluo** [comment]
Could it be caused by the authority value you passed in? May we know what exactly are you used for the authority parameter? It should be in the form of "https://login.microsoftonline.com/your_tenant" (with one path), rather than "https://login.microsoftonline.com/your_tenant/v2.0".

**Comment by bobbrady** [comment]
Thanks @rayluo , 

Here's what I've been using:
`https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token`

I'll try your recommended `https://login.microsoftonline.com/your_tenant` report back, closing issue if it fixes it.

**Comment by bobbrady** [comment]
Thanks @rayluo , I used your recommended authority URL format and I'm getting success with v1.0.0.

Much appreciated!

**Comment by synergiator** [comment]
Hi there,

I have tested the certificate sample both for recent ADAL and MSAL; it seems to work i.e. I get the token in both cases, but with MSAL I have get this error. 

I've used the authority URL https://login.microsoftonline.com/your_tenant.



Log excerpt:

```
DEBUG:msal.token_cache:event={
    "client_id": "XXXXXXXX",
    "data": {
        "scope": [
            "https://graph.microsoft.com/.default"
        ]
    },
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://graph.microsoft.com/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/XXXXXX/oauth2/v2.0/token"
}
..
Traceback (most recent call last):
  File "confidential_client_certificate_sample.py", line 68, in <module>
    graph_data = requests.get(  # Use token to call downstream service
  File "/home/user/.virtualenvs/msal/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)


```

**Comment by rayluo** [comment]
@synergiator So you were able to acquire a token. It is just that the token is somehow not accepted in the graph API call. We won't know for sure, I would suggest you to double check the scopes you use, and/or the Graph API call response. In case the Graph call just redirects you to MS Graph "homepage", it might potentially be a human-readable page containing a meaningful error message?). You might better ask that question in a Graph support forum.

Regardless, this conversation is not relevant to the original issue here. I'm going to lock this conversation. If you encounter new issues about MSAL Python, please create a new issue for your topic.
