### ISSUE TITLE
token result: include username in the auth result

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-library-for-python#13]
Azure CLI needs to know what user account name used to go through the authentication process. In ADAL, the result contains the "user_id" which is pretty good, but MSAL no longer includes such information, nor does the token cache supports such convenient method. 
For now, Azure CLI does join query by itself to figure out as demo'd by the pseudo code below, but that appears more like a hack to me
```python
   matches = app.token_cache.find('AccessToken', query={'secret': token_entry['access_token']})
   app.token_cache.find('Account', query={'home_account_id': matches[0]['home_account_id']})
```

**Comment by rayluo** [comment]
I agree with you. The workaround above is too hacky. You should not need to jump through 2 hoops (which I mean 2 searches) to get what you want.

Let me guess. In your workaround, after you locate that Account, what would you do next? Do you use its `username` field only? Or perhaps `local_account_id` thing too? [Those two are actually derived from the id token.](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/v0.1.0/msal/token_cache.py#L100-L102) So a conceptually more correct approach is to decode the id token and get the fields you want.

If those 2 fields are what you want, we can consider add an id token decode helper in this library.

**Comment by rayluo** [comment]
This happens to be solved by one of our recent effort on a seemingly separated topic: to add id token decode (and validate) behavior (which is a [long-awaited feature in itself since ADAL Python](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/172)). We introduce a new key-value pair in the return value of MSAL Python's acquire_token_by_xyz() methods:

```
{
    "token_type": "Bearer",
    "access_token": "eyJ0...",
    "refresh_token": "OAQ...",
    "id_token": "eyJ...",
    ...

    "id_token_claims": {
        "aud": "289...",
        "iss": "https://login.microsoftonline.com/f645ad92-e38d-4d1a-b510-d1b09a74a8ca/v2.0",
        "iat": 1559626249,
        "nbf": 1559626249,
        "exp": 1559630149,
        "aio": "ATQ...",
        "name": "Cloud IDLAB Basic User",
        "oid": "9f4...",
        "preferred_username": "idlab@msidlab4.onmicrosoft.com",
        "sub": "4mB...",
        "tid": "f64...",
        "uti": "91H...",
        "ver": "2.0"
    }
}
```

In other words, the "username" that Azure CLI wants, can be retrieved by:
 
```python
    result = app.acquire_token_by_xyz(...)

    username = result.get("id_token_claims", {}).get("preferred_username")  # Note:
        # 1. The "id_token_claims" would only be available in acquire_token_by_xyz(),
        #    but not in acquire_token_silent(..., acount, ...),
        #    which shouldn't matter because, in acquire_token_silent() you already know the account beforehand.

        # 2. Empirically, its "preferred_username" would be available in most AAD response.
        # Nonetheless, in the snippet above, we use .get(...) as a safe pattern.
```
