### ISSUE TITLE
Interactive auth using system browser

### ISSUE THREAD

**Issue by navyasric** [AzureAD/microsoft-authentication-library-for-python#138]

**Comment by sharanraj1996** [comment]
Really looking forward to this enhancement. Is this enhancement planned for the next release?

**Comment by rayluo** [comment]
@sharanraj1996 Thanks for your interest on this. We will get back to this, though not necessarily in the very next release. Meanwhile, you can take a look into our [Device Flow sampe](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.3.0/sample/device_flow_sample.py). It is actually quite easy and, depends on your usage scenario, it might even be a better solution.

**Comment by sharanraj1996** [comment]
> @sharanraj1996 Thanks for your interest on this. We will get back to this, though not necessarily in the very next release. Meanwhile, you can take a look into our [Device Flow sampe](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.3.0/sample/device_flow_sample.py). It is actually quite easy and, depends on your usage scenario, it might even be a better solution.

As suggested tried out "Device Flow sample", Thank you @rayluo for the suggestion.

**Comment by FelixS90** [comment]
A workaround is sketched in [this issue](https://github.com/Azure/azure-sdk-for-python/issues/13834) (see `get_auth_response`).
