### ISSUE TITLE
trace: `verify` flag is not wired up to turn off cert validation for capturing traces

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-library-for-python#15]
This is important to capture traces through proxy tools like fiddler which uses self-signed certificate.
The [verify](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L81) appears designed for such purpose, but it is not wired up in oauth2.py, nor is wired up in other places like `authority.py`

**Comment by rayluo** [comment]
OK I'll take a look. By the way, you are using similar steps like [this](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Client-credentials) to generate your self-signed cert, aren't you?

**Comment by yugangw-msft** [comment]
do this, which might be simpler
  > install azure-cli
  > run `az ad sp create-for-rbac -n http://you-great-sp --create-cert --skip-assignment`
