### ISSUE TITLE
running device_flow_sample gets error

### ISSUE THREAD

**Issue by rfernand2** [AzureAD/microsoft-authentication-library-for-python#154]
I am trying to run the "device_flow_sample.py" app, having substituted my AAD-registered app's client_id for the client_id in the sample.  When I run the resulting app, I get the following error:

> Exception has occurred: ValueError
> Fail to create device flow. Err: {
>     "error": "invalid_request",
>     "error_description": "AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 4bec3e19-5ffa-451c-b56c-40efd22b2e00\r\nCorrelation ID: c93c734e-cc04-41ec-a18f-aa79616dd062\r\nTimestamp: 2020-02-04 23:59:10Z",
>     "error_codes": [
>         50059
>     ],
>     "timestamp": "2020-02-04 23:59:10Z",
>     "trace_id": "4bec3e19-5ffa-451c-b56c-40efd22b2e00",
>     "correlation_id": "c93c734e-cc04-41ec-a18f-aa79616dd062",
>     "interval": 5,
>     "expires_in": 1800,
>     "expires_at": 1580862550.924673,
>     "_correlation_id": "c93c734e-cc04-41ec-a18f-aa79616dd062"
> }
>   File "C:\github\ExperimentTools\tryStuff\authenicationTest.py", line 73, in <module>
>     "Fail to create device flow. Err: %s" % json.dumps(flow, indent=4))
>   File "C:\anaconda3\envs\exper\Lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\anaconda3\envs\exper\Lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\anaconda3\envs\exper\Lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)

Is that the correct kind of client_id?  I also tried by username's azure object id, but same error resulted.  I am trying to find a way to granting Azure Storage or Key Vault permission to my python app's users via AAD.  Thanks.

**Comment by rayluo** [comment]
Could it possibly be the same as #141 ?

**Comment by rfernand2** [comment]
This *does* sound the same.  So, what should I be using for the "client_id" and "authority_url"?  Is this something I get from the Azure Portal?

**Comment by rfernand2** [comment]
OK, when I use the client_id of my AAD-registered app, and replace the "common" in the authority url with my app's tenant id, it then returns from "app.acquire_token_by_device_flow()" with the error: 

> invalid_client
> AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
> Trace ID: 8ebae900-e2c2-4eea-91ed-d20a3ffb4c00
> Correlation ID: 42c3733e-4a9c-40f7-b80e-05798f2bb626
> Timestamp: 2020-02-05 01:19:06Z
> 42c3733e-4a9c-40f7-b80e-05798f2bb626

**Comment by rayluo** [comment]
Perhaps you can try to follow the screenshot in [this section](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis#configure-platform-settings-for-your-application), and change its bottom-right toggle to "treat application as public client", and see how it pan out?

**Comment by rfernand2** [comment]
Checking the "public client" button fixed the problem, thanks!  I am now able to get AAD info using the browser / device code authentication.
