### ISSUE TITLE
How can I use this for non-graph apis?

### ISSUE THREAD

**Issue by nixomose** [AzureAD/microsoft-authentication-library-for-python#155]
I couldn't find a better place to post this question, sorry if this is the wrong venue.
I got this sample working, and it allows me to query all sorts of graph api information.
But I need to access other azure rest apis like the azure management network... 
https://docs.microsoft.com/en-us/python/api/overview/azure/network/management?view=azure-python

whenever I make a request like this:

requests.get("https://management.azure.com/subscriptions/" + sub + "/resourcegroups/" + rg + "/providers/Microsoft.Authorization/permissions?api-version=2015-07-01",
            headers={'Authorization': 'Bearer ' + result['access_token']},) .json()

I get 
{
  "error": {
    "code": "AuthenticationFailed",
    "message": "Authentication failed."
  }
}
I have enabled what I believe are the appropriate apis in the  api permissions of my client app.
I'm not sure what else I have to authenticate with.
Help?

**Comment by henrik-me** [comment]
@nixomose Is the token you have obtained for that resource and that set of scopes that you are requesting? I'm not sure how fine grained the permissions are for the api mentioned however you should be requesting access to the right scope. Default scope would likely be: "https://management.azure.com/.default"

Can you provide a correlation id and a time stamp?

**Comment by nixomose** [comment]
so I finally got it all worked out.
it turns out that there's a v1 api and a v2 api for the oauth2 stuff.
and I was looking at the wrong example for what to try because there are so many of them.
once I got the right one, I got it to work, thanks for your help.

for anybody coming across this, I followed this:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by rayluo** [comment]
Sounds like @nixomose you are implementing oauth2 logic? In case you haven't already noticed, the MSAL sdk is designed to make that part easy for you. And this is [a sample web app based on MSAL Python](https://github.com/Azure-Samples/ms-identity-python-webapp), which uses the auth code flow under the hood.

Regardless, happy hacking!
