### ISSUE TITLE
How to properly pass domain_hint?

### ISSUE THREAD

**Issue by alex-mason-jdas** [AzureAD/microsoft-authentication-library-for-python#158]
Is there documentation or sample that can clearly show how to pass domain_hint as a query parameter when using MSAL for Python?

**Comment by rayluo** [comment]
You are talking about [this feature](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oapx/86fb452d-e34a-494e-ac61-e526e263b6d8). Sorry, we do not currently expose this parameter. It will not be difficult to add it, though.

**Comment by rayluo** [comment]
@nwalsh1995 , this feature has been merged. We'll link this issue to an upcoming release branch soon. Please stay tuned with notification from this conversation. Thanks!
