### ISSUE TITLE
[Feature Request] Support confidential client being authenticated by a signed assertion

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-python#161]
MSAL .Net already supports [confidential client authenticated by a signed assertion](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Assertions#signed-assertions), with the API `.WithClientAssertion(...)`.

[A use case for this feature is mentioned in a PR in ADAL Python](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/196#issue-261860814). Now that ADAL Python does not accept new features any more, we can and should implement this in MSAL Python.

Internal feature request: [Feature 1408908: MSAL Python libraries supports service identity federation / assumed identity](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1408908)

**Comment by stueynz** [comment]
It would appear that class: `ConfidentialClientApplication` supports authentication by EITHER client secret OR signed assertion depending upon what you put into the the `client_credential` parameter upon initialisation.

Checkout the source beginning at lines 104 of https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py

**Comment by rayluo** [comment]
Hi @stueynz ,

[The content you found](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.3.0/msal/application.py#L107-L114), is actually talking about `ConfidentialClientApplication` supports authentication by either client secret, or a certificate. That certificate will then be used to create a signed assertion. That part already works, if that is what you need.

This feature request, though, is about to begin with an already-signed assertion. This feature is not yet supported.
