### ISSUE TITLE
How to use/add internal PKI cert (outbound public cert chain) to securely make the connection.

### ISSUE THREAD

**Issue by kasirajans** [AzureAD/microsoft-authentication-library-for-python#164]
We do proxy all outbound request and urllib connection is getting failed.  Is any way I can add our public cert in the URL request in MSAL lib? Tried to make changes to request function with verfiy=Flase but still no luck.

**Comment by rayluo** [comment]
MSAL Python is currently using the requests library for its HTTP traffic, and I believe MSAL already wire up the `verify` parameter and relay it to the underlying requests. Perhaps you can find some [verify info from requests's doc](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification)?

**Comment by kasirajans** [comment]
Okay! Can you let me know where exactly do I need to add PKI public cert .pem in MSAL ?

**Comment by rayluo** [comment]
If you mean how to "add PKI public cert .pem in ~MSAL~ [requests](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification)?" I haven't personally done that before, but I found [this Q&A](https://stackoverflow.com/questions/38182773/add-single-certificate-to-requests) might be helpful.

Once you figure the above thing out, then this should work: each `acquire_token_by_xyz(...)` method in MSAL accepts arbitrary extra parameters, which will then be relayed to the underlying requests. So, for example, you could do `acquire_token_by_username_password(..., verify=FOO)`, and the FOO part would be the same as your solution in requests.

**Comment by navyasric** [comment]
Closing as the issue has been answered.
