### ISSUE TITLE
[Feature Request] Client capabilities support

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-python#174]
Smart Session Management (SSM) sometimes referred to as the long lived tokens (LLT) scenario require MSAL to allow developers to resolve challenges (formatted as claims request parameters) to be resolved silently rather than interactively.  Current releases of MSAL assume that interaction is required whenever a claims request parameter is included in the request.  

This change in behavior requires the client to indicate that it's aware of a new calling pattern relative to the use of MSAL.

See additional details of requirements in:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1545

API/Design details:
https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=%2FClientCapabilities%2Foverview.md&version=GBdev
**Is your feature request related to a problem? Please describe.**

Related internal work item:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/824806

**Comment by rayluo** [comment]
Self-note from recent research:

* Happen to notice that [a related internal work item for MSAL Python](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/824810) was marked as "declined". But I guess we are now still planning to implement this.

* Per [API Design/Review conclusion](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=%2FClientCapabilities%2Foverview.md&version=GBdev&_a=preview), "Client Capability" is about the requirements below, Nothing more. Nothing less.
  1. `class ClientApplication` constructor accepting a list of arbitrary strings provided by caller.
     (Note: So that the `CP1` magic string (more on this later) should be provided by caller, rather than hardcoded inside MSAL.)
  2. wrap them inside `claims` parameter, like this: `{"accessToken":{"xms_cc": ["CP1"]}}`

  3. merge it with the actual [`claims` parameter](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) (if any),
  4. now send them to authorize and token endpoint.

* For what it's worth, "Client Capability" will mainly be used by another feature named "[Claims Challenge (this doc contains a diagram)](https://microsoft.sharepoint.com/:w:/t/aad/protocols/ERSWYtOQB45GgG4e2q3Cz00B6C36zi4gAs6JhdQG_wvVeQ?rtime=yEUj_nvd1kg&wdLOR=cB0CF5D1C-739A-4A91-983A-DBBDB9E775A6)", which is in term used to implement [CAE (Continuous Access Evaluation)](https://microsoft.sharepoint-df.com/:w:/r/teams/SmartSessionManagementforOfficeClients/_layouts/15/guestaccess.aspx?e=h2WxI7&share=EVL1XDzeRY9BlFQqw8ScOGABaKZTBFxWrshBeyhRqHqOzg).
  Given that the application would need to be aware of these, MSAL does not need to do anything special here. This part is opaque to MSAL.
