### ISSUE TITLE
TypeError when acquiring token for client using client credentials flow

### ISSUE THREAD

**Issue by mowiena** [AzureAD/microsoft-authentication-library-for-python#190]
To reproduce issue: 

Created ConfidentialClient to get token using client credential flow.
```
client = ConfidentialClientApplication(
    client_id,
    client_credential=client_secret,
    authority=authority,
    validate_authority=False,
    verify=False,
    token_cache=None
response = client.acquire_token_for_client([“https://graph.microsoft.com/.default”], verify=False)
)
```
On runtime, library returns `TypeError: sequence item 3: expected str instance, tuple found`. The error is raised for this [line](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/token_cache.py#L59)

**Comment by rayluo** [comment]
The item 3 in that sequence is the `client_id`. Indeed I can reproduce this issue, when/if I purposely use a tuple as my `client_id`. Was that the case here?

**Comment by mowiena** [comment]
There was an unintended trailing comma after the client ID string. Thanks @rayluo
