### ISSUE TITLE
MSAL Library Bearer Tokens Invalid For Azure REST API

### ISSUE THREAD

**Issue by gyamada619** [AzureAD/microsoft-authentication-library-for-python#199]
A bearer token obtained using MSAL, when passed to the Azure REST API, returns "Authorization Failed". We have been forced to use the ADAL library for Python, which uses the v1.0 endpoints for our Azure AD app. Please allow tokens from MSAL to be used with the Azure REST API!

**Comment by gyamada619** [comment]
@bennyx93 I filed an issue here.

**Comment by gyamada619** [comment]
For those wondering, this can be fixed by following https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-python-adal-msal.

You'll need to use the scope `https://management.azure.com/.default`, but this cannot be combined with resource-specific scopes like `User.Read`.

**Comment by rayluo** [comment]
@gyamada619 Glad that you figured it out. Also a FYI, we [improved how refresh token (RT) would be migrated into MSAL Python 1.3.0, released days ago](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.3.0).
