### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by adamchainz** [AzureAD/microsoft-authentication-library-for-python#202]
I can't find a changelog for this repo, please add one to make it easy for users to upgrade. It's also worth adding a link in your setup.py or setup.cfg's `project_urls` to make it really easy to find: https://github.com/adamchainz/apig-wsgi/blob/master/setup.cfg#L11

**Comment by rayluo** [comment]
We chose to not maintain a changelog, while we already got one, for free, in [this repo's release history hosted on github](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases).

Do you happen to know whether such a page would also be rendered well in PyPI? Feel free to send a PR to us.

**Comment by adamchainz** [comment]
Ah right. In my experience most Python devs don't check the repo release list - releases come from PyPI. It's not rendered on PyPI, it's a link on the left hand side. See my package on PyPI: https://pypi.org/project/apig-wsgi/ . You should also add a link to the docs and the README.

I don't have time to send a PR but I hope you can make the change.

**Comment by rayluo** [comment]
If it will be rendered ONLY as just a link on the left hand side, sure we can totally do that, without any undesirable side effect.

Can you also enlighten me on what is the PyPI behavior on rendering the "History" part at the bottom of [your package on PyPI](https://pypi.org/project/apig-wsgi/)? Their raw content is in history.rst, but then I could not find where your setup explicitly reference it (except [that line](https://github.com/adamchainz/apig-wsgi/blob/master/setup.cfg#L11)).

I could try something like this in this repo:

```
project_urls =
    Changelog = https://github.com/AzureAD/microsoft-authentication-library-for-python/releases
```

Hopefully PyPI would NOT attempt to render at the bottom of the project page. Do you have any insight for this?

**Comment by adamchainz** [comment]
> Can you also enlighten me on what is the PyPI behavior on rendering the "History" part at the bottom of your package on PyPI? Their raw content is in history.rst, but then I could not find where your setup explicitly reference it (except that line).

Ah, I was previously explicitly including that in the `long_description` explicitly. I removed it recently: https://github.com/adamchainz/apig-wsgi/commit/3e9b978d7941a513f8cebf3ee85cc8185b7959ed#diff-380c6a8ebbbce17d55d50ef17d3cf906 . It hasn't been updated on PyPI since I haven't made a release since.

> Hopefully PyPI would NOT attempt to render at the bottom of the project page. Do you have any insight for this?

That code LGTM, and no, it will not.
