### ISSUE TITLE
acquire_token_by_refresh_token - AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by mamilov** [AzureAD/microsoft-authentication-library-for-python#208]
I'm getting the following error when trying to request an access_token via refreh_token:  

```
File "/usr/local/lib/python3.7/site-packages/msal/application.py", line 730, in acquire_token_by_refresh_token
    on_updating_rt=False,
  File "/usr/local/lib/python3.7/site-packages/msal/oauth2cli/oauth2.py", line 528, in obtain_token_by_refresh_token
    (on_removing_rt or self.on_removing_rt)(token_item)  # Discard old RT
  File "/usr/local/lib/python3.7/site-packages/msal/token_cache.py", line 241, in remove_rt
    assert rt_item.get("credential_type") == self.CredentialType.REFRESH_TOKEN
AttributeError: 'str' object has no attribute 'get'
```

Does anybody know why this happens? The refresh token should be valid (tested locally).

**Comment by mamilov** [comment]
I was able to fix the problem myself. This error occurs when the refreshtoken belongs to user from another tenant that cannot login to my tenant. Solved it by setting the authority to 'https://login.microsoftonline.com/common'.

**Comment by abhidnya13** [comment]
Hey @mamilov, Great that you were able to solve the issue here. Just curious, can you share your usecase ? I see you are using acquire_token_by_refresh_token. Are you trying to migrate tokens from ADAL to MSAL ?

**Comment by rayluo** [comment]
I have same curiosity as Abhi to know whether @mamilov is using this for token migration. And if so, where were those existing RTs from. :-)

Other than that, thanks @mamilov for bringing this to our attention. Our library should not raise exception even in this unplanned corner case "This error occurs when the refreshtoken belongs to user from another tenant that cannot login to my tenant". I've prepared an improvement. @mamilov you can have an early bird access to it by `pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@robust-migration`. Please let us know whether that works for you.
