### ISSUE TITLE
Add public convenience string constants for endpoints of each cloud (sovereign and public)

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-python#221]
**Context**
Customers have had difficulty finding the right documentation pages:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide#endpoint-mapping
https://docs.microsoft.com/en-us/azure/china/resources-developer-guide#check-endpoints-in-azure

**See also other libraries exposing these:**
- [obj-c](https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALAzureCloudInstance.html) 
- [.net](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet)

**Reference:**
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1063014

**Other:**
https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/258

**Comment by rayluo** [comment]
> See also other libraries exposing these:
> 
> * [obj-c](https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALAzureCloudInstance.html)
> * [.net](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet)

OK. After comparison, we think the [.net](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet) naming matches this [AAD national cloud document](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints) closely. We will adopt it.

**Comment by jmehnle** [comment]
Any plans to implement this?

**Comment by rayluo** [comment]
> Any plans to implement this?

Hi @jmehnle , a new usage pattern is documented in [our doc staging site (please search the keyword "authority (str)") in this page](https://msal-python.readthedocs.io/en/docs-staging/). It will be included in our late Nov release.

**Comment by jmehnle** [comment]
That seems like a great solution. Thanks, @rayluo and team! Looking forward to that late-November release.
