### ISSUE TITLE
Acquiring access_token fails for Spring 2020 Windows Virtual Desktop client application

### ISSUE THREAD

**Issue by jgrzelak** [AzureAD/microsoft-authentication-library-for-python#222]
**Issue description**
We try to use the MSAL library to authenticate a Spring 2020 Windows Virtual Desktop client application user (client_id = "a85cf173-4192-42f8-81fa-777a763e6e2c"). The object returned by the PublicClientApplication's **acquire_token_by_username_password** function contains: "error": "invalid_client" and "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'."

The code looks like the following:

```python
TENANT    = "xxxxxx.onmicrosoft.com"
USERNAME  = "xxxxxx@xxxxxx.onmicrosoft.com"
PASSWORD  = "xxxxxx"
CLIENT_ID = "a85cf173-4192-42f8-81fa-777a763e6e2c"
RESOURCE  = "https://www.wvd.microsoft.com/.default"

from msal import PublicClientApplication
import logging
import json

logging.basicConfig(level=logging.DEBUG)

app    = PublicClientApplication(CLIENT_ID, authority = "https://login.microsoftonline.com/" + TENANT)
result = app.acquire_token_by_username_password(USERNAME, PASSWORD, {RESOURCE})

print("-------------------")
print(json.dumps(result, indent=4))
```
The above scripts (when using real tenant name, username and password) gives following output (line breaks added for better readability):

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /xxxxxx.onmicrosoft.com/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1523
DEBUG:msal.authority:openid_config = 
{
	'token_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/token',
	'token_endpoint_auth_methods_supported': [
		'client_secret_post',
		'private_key_jwt',
		'client_secret_basic'
	],
	'jwks_uri': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/discovery/v2.0/keys',
	'response_modes_supported': [
		'query',
		'fragment',
		'form_post'
	],
	'subject_types_supported': [
		'pairwise'
	],
	'id_token_signing_alg_values_supported': [
		'RS256'
	],
	'response_types_supported': [
		'code',
		'id_token',
		'code id_token',
		'id_token token'
	],
	'scopes_supported': [
		'openid',
		'profile',
		'email',
		'offline_access'
	],
	'issuer': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/v2.0',
	'request_uri_parameter_supported': False,
	'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo',
	'authorization_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/authorize',
	'http_logout_supported': True,
	'frontchannel_logout_supported': True,
	'end_session_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/logout',
	'claims_supported': [
		'sub',
		'iss',
		'cloud_instance_name',
		'cloud_instance_host_name',
		'cloud_graph_host_name',
		'msgraph_host',
		'aud',
		'exp',
		'iat',
		'auth_time',
		'acr',
		'nonce',
		'preferred_username',
		'name',
		'tid',
		'ver',
		'at_hash',
		'c_hash',
		'email'
	],
	'tenant_region_scope': 'EU',
	'cloud_instance_name': 'microsoftonline.com',
	'cloud_graph_host_name': 'graph.windows.net',
	'msgraph_host': 'graph.microsoft.com',
	'rbac_url': 'https://pas.windows.net'
}
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /common/userrealm/xxxxxx@xxxxxx.onmicrosoft.com?api-version=1.0 HTTP/1.1" 200 174
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/token HTTP/1.1" 401 530
-------------------
{
    "error": "invalid_client",
    "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: ea7aaae7-4bd7-4fac-9257-400eb9465200\r\nCorrelation ID: 75e78a15-1ea4-424f-b589-794076435c9c\r\nTimestamp: 2020-07-02 13:02:26Z",
    "error_codes": [
        7000218
    ],
    "timestamp": "2020-07-02 13:02:26Z",
    "trace_id": "ea7aaae7-4bd7-4fac-9257-400eb9465200",
    "correlation_id": "75e78a15-1ea4-424f-b589-794076435c9c",
    "error_uri": "https://login.microsoftonline.com/error?code=7000218"
}
```

**Expected behavior**
We expect to get an access_token, as we do when authenticating the same user with Fall 2019 Windows Virtual Desktop client. 

**What you see instead**
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

**The MSAL Python version used**
```
python3 -c "import msal; print(msal.__version__)"
1.4.1
```

**Additional context**
All works fine when the same code will be used to authenticate a Fall 2019 Windows Virtual Desktop client application user (client_id = "fa4345a4-a730-4230-84a8-7d9651b86739"). 

The only difference are the two following parameters:

```python
CLIENT_ID = "fa4345a4-a730-4230-84a8-7d9651b86739"
RESOURCE  = "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/.default"
```

The output is similar to the following then:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /xxxxxx.onmicrosoft.com/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1523
DEBUG:msal.authority:openid_config = 
{
	'token_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/token',
	'token_endpoint_auth_methods_supported': [
		'client_secret_post',
		'private_key_jwt',
		'client_secret_basic'
	],
	'jwks_uri': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/discovery/v2.0/keys',
	'response_modes_supported': [
		'query',
		'fragment',
		'form_post'
	],
	'subject_types_supported': [
		'pairwise'
	],
	'id_token_signing_alg_values_supported': [
		'RS256'
	],
	'response_types_supported': [
		'code',
		'id_token',
		'code id_token',
		'id_token token'
	],
	'scopes_supported': [
		'openid',
		'profile',
		'email',
		'offline_access'
	],
	'issuer': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/v2.0',
	'request_uri_parameter_supported': False,
	'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo',
	'authorization_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/authorize',
	'http_logout_supported': True,
	'frontchannel_logout_supported': True,
	'end_session_endpoint': 'https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/logout',
	'claims_supported': [
		'sub',
		'iss',
		'cloud_instance_name',
		'cloud_instance_host_name',
		'cloud_graph_host_name',
		'msgraph_host',
		'aud',
		'exp',
		'iat',
		'auth_time',
		'acr',
		'nonce',
		'preferred_username',
		'name',
		'tid',
		'ver',
		'at_hash',
		'c_hash',
		'email'
	],
	'tenant_region_scope': 'EU',
	'cloud_instance_name': 'microsoftonline.com',
	'cloud_graph_host_name': 'graph.windows.net',
	'msgraph_host': 'graph.microsoft.com',
	'rbac_url': 'https://pas.windows.net'
}
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /common/userrealm/xxxxxx@xxxxxx.onmicrosoft.com?api-version=1.0 HTTP/1.1" 200 174
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/token HTTP/1.1" 200 4163
DEBUG:msal.token_cache:event={
    "client_id": "fa4345a4-a730-4230-84a8-7d9651b86739",
    "data": {
        "password": "********",
        "scope": [
            "offline_access",
            "openid",
            "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/.default",
            "profile"
        ],
        "username": "********"
    },
    "grant_type": "password",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiI1NTA1NmNmZS01NGIxLTRmYmItODAwZi05MjllNjAwY2RmMDMiLCJ1dGlkIjoiNmYyMzljOTItYTIzMy00YjZiLTg3NWItNDk0MTdlOTk3ZWVmIn0",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZ.....",
        "refresh_token": "********",
        "scope": "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/user_impersonation https://mrs-prod.ame.gbl/mrs-RDInfra-prod/.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/user_impersonation",
        "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/oauth2/v2.0/token"
}
-------------------
{
    "token_type": "Bearer",
    "scope": "https://mrs-prod.ame.gbl/mrs-RDInfra-prod/user_impersonation https://mrs-prod.ame.gbl/mrs-RDInfra-prod/.default",
    "expires_in": 3599,
    "ext_expires_in": 3599,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNzW.....",
    "refresh_token": "OAQABAAAAAAAGV_bv21oQQ4ROqh0_1-tACgBXEsq.....",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlNzWn.....",
    "client_info": "eyJ1aWQiOiI1NTA1NmNmZS01NGIxLTRmYmItODAwZi05MjllNjAwY2RmMDMiLCJ1dGlkIjoiNmYyMzljOTItYTIzMy00YjZiLTg3NWItNDk0MTdlOTk3ZWVmIn0",
    "id_token_claims": {
        "aud": "fa4345a4-a730-4230-84a8-7d9651b86739",
        "iss": "https://login.microsoftonline.com/6f239c92-a233-4b6b-875b-49417e997eef/v2.0",
        "iat": 1593695420,
        "nbf": 1593695420,
        "exp": 1593699320,
        "aio": "ATQAy/8QAAAAyYQY9uvPvMDl4zokMlT+KXFdYUUAmvxyJXymE36jxebyuuuFE0zf6sVv1eNaSrxf",
        "name": "Jarek Grzelak",
        "oid": "55056cfe-54b1-4fbb-800f-929e600cdf03",
        "preferred_username": "xxxxxx@xxxxxx.onmicrosoft.com",
        "sub": "UiVPnkEyEg1VqaYgdjywnJG82-_077GgEpS44xIu8yM",
        "tid": "6f239c92-a233-4b6b-875b-49417e997eef",
        "uti": "wUv4uUkTgka71NjlLddTAA",
        "ver": "2.0"
    }
}
```

**Comment by rayluo** [comment]
Hi Jarek, thanks for sharing your minimal code snippet in this issue! So you have two app IDs with same implementation, one works and the other doesn't. It is likely that some configuration of these 2 apps are not identical.

In case you haven't already noticed, [this comment in our off-the-shelf sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.4.1/sample/username_password_sample.py#L55-L56) describes some common topics. Please see if its "Setup" section would help here?

**Comment by jgrzelak** [comment]
Hello Ray,

yes, we need to perform username+password based authentication for two WVD client apps. One works, the other doesn't.

The same issue happens when executing the ``username_password_sample.py`` script (with the Graph API call commented out):
```
INFO:root:No suitable token exists in cache. Let's get a new one from AAD.
invalid_client
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 9eeebba5-ec94-4df3-9406-b67f0a8f6500
Correlation ID: eb63cd57-7341-4e54-9e71-ddb5cd70f17e
Timestamp: 2020-07-02 22:37:23Z
eb63cd57-7341-4e54-9e71-ddb5cd70f17e
```

I pass to the script name of a configuration file for Spring 2020 WVD client:
```
{
    "authority": "https://login.microsoftonline.com/xxxxxx.onmicrosoft.com",
    "client_id": "a85cf173-4192-42f8-81fa-777a763e6e2c",
    "username": "xxxxxx@xxxxxxx.onmicrosoft.com",
    "password": "xxxxxx",
    "scope": ["https://www.wvd.microsoft.com/.default"]
}
```

Passing a file containing the configuration appropriate for the Fall 2019 WVD client application allows successful access_token retrieval.

**Comment by rayluo** [comment]
One of the reason of that symptom was documented here. Can you check its screenshot at the bottom and let us know whether that was the culprit?

> In case you haven't already noticed, [this comment in our off-the-shelf sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.4.1/sample/username_password_sample.py#L55-L56) describes some common topics. Please see if its "Setup" section would help here?

**Comment by jgrzelak** [comment]
Not sure if I get what you mean... All I see under [this hyperlink](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.4.1/sample/username_password_sample.py#L55-L56) is the ``username_password_sample.py`` off-the-shelf example. Just 72 lines of code. I do not see any comments (other than the comments in Python code) nor screenshots there...

**Comment by rayluo** [comment]
That is strange. That link contains `...#L55-L56` at the end, which is supposed to automatically scroll to - and highlight - line 55 and 56, which are quoted below:

    # See this page for constraints of Username Password Flow.
    # https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication

<sub>I know I could have directly given you that wiki page link, but I was just trying to show you the trace to discover those info.</sub>

**Comment by jgrzelak** [comment]
OK, got you now.
Regarding the Username/Password flow constrains and the application with client_id = "a85cf173-4192-42f8-81fa-777a763e6e2c":
- The user accounts we try with exist in Azure AD, so they are "work and school accounts", correct?
- Multi-factor authentication will not be used. Also, I don't think that conditional access is enabled (I see few baselines policies defined, but all are 'off').
- When I go to **Permissions** of the Windows Virtual Desktop Client (Spring 2020) enterprise application ("a85cf173-4192-42f8-81fa-777a763e6e2c") then I see the following: _The ability to consent to this application is disabled as the app does not require consent or the app developer hasn't configured permissions in the App registration. Granting consent only applies to applications requiring permissions to access your resources._
- FYI: Under **Permissions** of the Windows Virtual Desktop Client (Fall 2019) enterprise application ("fa4345a4-a730-4230-84a8-7d9651b86739"), where the Username/Password authentication works with the MSAL Python module, I see the following:
= API name: Windows Azure Active Directory
= Permission: Sign in and read user profile
= Type: Delegated
= Granted through: Admin consent
= Granted by: An administrator
= ----
= API name: Windows Virtual Desktop AME
= Permission: Access Windows Virtual Desktop
= Type: Delegated
= Granted through: Admin consent
= Granted by: An administrator

In the **Setup** section, the article then states: _Microsoft identity platform supports username password flow on public client application only._ I don't know how can I check if the "a85cf173-4192-42f8-81fa-777a763e6e2c" application is a public or confidential client... Do you know how to check it, or should I create a support request through Azure Portal?

**Comment by jgrzelak** [comment]
One more thing: 
In the Wiki of of the MSAL.NET library I've found a [paragraph](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#invalid-client) confirming the suspicion, that the "a85cf173-4192-42f8-81fa-777a763e6e2c" application is possibly registered as confidential client application, not as a public client application, allowing the Username/Password authentication flow, but on the other hand I see some facts contradicting this theory...

I have analyzed the Sign-in logs of the Windows Virtual Desktop Client ("a85cf173-4192-42f8-81fa-777a763e6e2c") under our Azure AD tenant and found some interesting stuff. 

Here is a successful authentication attempt from Windows 10 native Remote Desktop client:

![obraz](https://user-images.githubusercontent.com/56913819/86611818-82a11c00-bfaf-11ea-804c-01da59852498.png)

The 'Authentication type' on the 'Authentication details' tab was: CloudOnlyPassword.

Now, a successful authentication attempt from HTM5-based Windows Virtual Desktop client:

![obraz](https://user-images.githubusercontent.com/56913819/86612325-415d3c00-bfb0-11ea-9fb9-3b5eeac6bffe.png)

The 'Authentication type' on the 'Authentication details' tab was CloudOnlyPassword too, in this case.

Now, a failed authentication request from Python with MSAL:

![obraz](https://user-images.githubusercontent.com/56913819/86612687-cba5a000-bfb0-11ea-8082-dc7db8c6b58e.png)

The 'Authentication type' on the 'Authentication details' tab was still CloudOnlyPassword, but why did the 'Client app' change to 'Browser' in this request?

Now, let's look at a successful Python/MSAL authentication request for the Windows Virtual Desktop (Fall 2019, "fa4345a4-a730-4230-84a8-7d9651b86739") client app. The 'Authentication type' is also CloudOnlyPassword in this case:

![obraz](https://user-images.githubusercontent.com/56913819/86613324-b7ae6e00-bfb1-11ea-9d95-02048d000327.png)

As you can see, here the 'Client app' is 'Mobile Apps and Desktop clients'. Is it something what depends on the MSAL PublicClientApplication configuration? What is making this difference? In all our experiments the Username/Password authentication attempts fail when the 'Client app' is set to 'Browser' and succeed when it is set to 'Mobile Apps and Desktop clients'...

**Comment by rayluo** [comment]
> In the **Setup** section, the article then states: _Microsoft identity platform supports username password flow on public client application only._ I don't know how can I check if the "a85cf173-4192-42f8-81fa-777a763e6e2c" application is a public or confidential client... Do you know how to check it, or should I create a support request through Azure Portal?

In that [Setup section](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication#setup), there is also a screenshot. Could it be somehow that screenshot was NOT displayed in your browser? The toggle switch in that screenshot is the way to check/set it.


> Now, a failed authentication request from Python with MSAL:
> ...
>  The 'Authentication type' on the 'Authentication details' tab was still CloudOnlyPassword, but why did the 'Client app' change to 'Browser' in this request?
> 
> Now, let's look at a successful Python/MSAL authentication request for the Windows Virtual Desktop (Fall 2019, "fa4345a4-a730-4230-84a8-7d9651b86739") client app. The 'Authentication type' is also CloudOnlyPassword in this case:
> ...
> As you can see, here the 'Client app' is 'Mobile Apps and Desktop clients'. Is it something what depends on the MSAL PublicClientApplication configuration?

 I did not notice that `The 'Authentication type' on the 'Authentication details' tab was still CloudOnlyPassword` detail before. Given that it remains the same in both your successful and unsuccessful attempts, it is probably irrelevant.

The 'Client app' is indeed the suspect here. It does NOT depend on the MSAL PublicClientApplication (it is the other way around). Again, we would like to see your app's client type setting inside Azure Portal. Please refer to that Setup session and, if it does not work, please paste your app's configuration screenshot.

**Comment by jgrzelak** [comment]
Yes, I've seen the screenshot in the Setup section of the referenced article, but the challenge is that we are not the authors of the 'Windows Virtual Desktop Client' applications. We only develop a kind of front-end for these apps. Both, the 'Fall 2019' and the 'Spring 2020', variants are made by Microsoft. You can find them when you search the Azure Portal's Enterprise Applications for 'Windows Virtual Desktop Client':

![obraz](https://user-images.githubusercontent.com/56913819/86639917-0b34b200-bfda-11ea-89ed-c5a09f83ef70.png)

I do not see them under 'App registrations' of our Azure AD tenant. 

I'm glad that we have managed to find the 'suspect'. Thanks for your help. We will try to get in touch with the developers of the problematic "a85cf173-4192-42f8-81fa-777a763e6e2c" client app.

**Comment by rayluo** [comment]
> You can find them when you search the Azure Portal's Enterprise Applications for 'Windows Virtual Desktop Client'

I can not, and that's probably because I'm not in the same tenant you are in. Regardless, yes you or the app owner can cross-check those apps configuration with each other and also compare it to [our wiki's screenshot](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication#setup).

Feel free to ping back when/if you need more help.

**Comment by jgrzelak** [comment]
Hi Ray,
FYI: we've learned today that the "a85cf173-4192-42f8-81fa-777a763e6e2c" client app has been registered as a confidential client. No wonder that the username/password authentication didn't work...

Do you know any Python library which we could use for obtaining the OAuth 2.0 authorization code, which we then could pass to the `acquire_token_by_authorization_code()` function of MSAL's ConfidentialClientApplication to obtain the access_token?

**Comment by rayluo** [comment]
> Hi Ray,
> FYI: we've learned today that the "a85cf173-4192-42f8-81fa-777a763e6e2c" client app has been registered as a confidential client. No wonder that the username/password authentication didn't work...

OK. But then [our wiki's screenshot on how to setup](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication#setup) describes how to configure that confidential client to also be "treated as a public client" in this scenario. Does that not work you?

> 
> Do you know any Python library which we could use for obtaining the OAuth 2.0 authorization code, which we then could pass to the `acquire_token_by_authorization_code()` function of MSAL's ConfidentialClientApplication, to obtain the access_token?

I see what you are trying to explore other options here. I'm not aware any library for only acquiring the auth code, though. That would be a niche feature which, if being supported, would typically be included inside a bigger OAuth2 library. MSAL Python itself will support it in the future, in #138, which reminds me that you could also try [yet another alternative "Device Flow"](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/138#issuecomment-646870700).

**Comment by rayluo** [comment]
Answered. Closing.
