### ISSUE TITLE
Is there any reason that we set content-type for http get? 

### ISSUE THREAD

**Issue by kendung** [AzureAD/microsoft-authentication-library-for-python#226]
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/6bade9faf7c832a47b13c8ac3eeba75f4084190f/msal/mex.py#L46

The reason Why I asked this issue is because our http get traffic will be blocked by WAF within our environment.

**Comment by rayluo** [comment]
Good question! [That line exists in MSAL Python's predecessor, ADAL Python, since its day 1](https://github.com/AzureAD/azure-activedirectory-library-for-python/blame/1.2.4/adal/mex.py#L77). And MSAL Python inherited it. @abhidnya13 is taking a look to see whether we really need it.

**Comment by kendung** [comment]
@rayluo thanks for the quick response. I am looking forward to you guys investigation.

**Comment by kendung** [comment]
thanks again for the quick fix. @rayluo @abhidnya13
