### ISSUE TITLE
from msal import PublicClientApplication gives error

### ISSUE THREAD

**Issue by CoderOnWinks** [AzureAD/microsoft-authentication-library-for-python#241]
I am using the demo sample codes from your repo and i see issue in using PublicClientApplication. It says ImportError: cannot import name 'PublicClientApplication'. I have 1.4.3 MSAL installed in my system.

**Comment by rayluo** [comment]
Can you follow our [bug reporting template](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/new?assignees=&labels=&template=bug_report.md&title=) to give us more information?

**Comment by navyasric** [comment]
Closing due to no further information provided. Please reopen if needed.
