### ISSUE TITLE
Device code endpoint malformed for some authorities

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-python#242]
`ClientApplication._build_client` forms the device code endpoint with `urljoin`:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/f285074d6d5700457e7e80eed79560ab86c77a9a/msal/application.py#L234-L238

This assumes `authority.token_endpoint` does not have a trailing slash. The URL is incorrect when it does:

```
>>> urljoin("https://foo.bar/token", "devicecode")
'https://foo.bar/devicecode'
>>> urljoin("https://foo.bar/token/", "devicecode")
'https://foo.bar/token/devicecode'
```

`token_endpoint` comes directly from the authority's openid metadata:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/f285074d6d5700457e7e80eed79560ab86c77a9a/msal/authority.py#L94

So the upshot is that should an authority give its token endpoint with a trailing slash, as does my Azure Stack's authority, `ClientApplication.intiate_device_flow` will fail.

**Comment by rayluo** [comment]
Historically, there was no "device_authorization_endpoint" available from tenant discovery, so we had to hardcode such fragile logic. Now it seems AAD provides that info (see [this example](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration)).

I do not currently have an Azure Stack environment. @chlowell can you paste its openid configuration output, to let us see whether it also contain the device_authorization_endpoint?

**Comment by rayluo** [comment]
@chlowell confirmed offline that "both the Stack and ADFS servers I'm working with return device_authorization_endpoint".

@abhidnya13 let's refactor this to use the device endpoint returned from the discovery, and still fall back to the existing logic when/if that info is not available.
