### ISSUE TITLE
user login with MFA into federated app

### ISSUE THREAD

**Issue by ageekymonk** [AzureAD/microsoft-authentication-library-for-python#251]
Hi, 

  This is more of a query on how to use MSAL for user login to a client app. The user has MFA. I tried with 

`msal.PublicClientApplication(
    config["client_id"], authority=config["authority"]
)
result = app.initiate_device_flow(
         scopes=config["scope"])  
`

I am getting the following error.
`'error': 'invalid_grant', 'error_description': "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access`

**Comment by rayluo** [comment]
@abhidnya13 Can you help try to reproduce this with one of our MFA-required test account? I am not sure whether Device Flow is supposed to be blocked by MFA. If Device Flow can work with MFA account, then we do not have to suggest an other-than-device-flow way.

**Comment by abhidnya13** [comment]
@ageekymonk I tried reproducing this with one of our MFA test accounts and I am able to login and do the MFA using device code flow sample. Can you try using this [device code flow sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/device_flow_sample.py) and let us know if you are able to authenticate ?

**Comment by abhidnya13** [comment]
Closing this as more info is required to triage this. Feel free to re-open if needed.
