### ISSUE TITLE
PKCE Support

### ISSUE THREAD

**Issue by FelixS90** [AzureAD/microsoft-authentication-library-for-python#255]
**Description**
As of today, there does not seem to be a straightforward way to support [PKCE](https://tools.ietf.org/html/rfc7636) through the use of query parameters `code_challenge` and `code_challenge_method`. See "[Request an authorization code](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code)" and  "[Request an access token](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token)" for more information.

Is there some guideline of how to achieve this? Is there a work around?

**The MSAL Python version you are using**
`python -c "import msal; print(msal.__version__)"` gives 1.5.0

**Comment by FelixS90** [comment]
A workaround is sketched in the [linked issue](https://github.com/Azure/azure-sdk-for-python/issues/13834). However, as stated there, there is no nice integration of MSAL Python with `azure.storage.blob` and thus would need to go with REST API directly.

**Comment by csy08** [comment]
I just use this code 
```
code_verifier = re.sub('[^a-zA-Z0-9]+', '', urlsafe_b64encode(urandom(40)).decode('utf-8'))
code_challenge = sha256(code_verifier.encode('utf-8')).digest()
code_challenge = urlsafe_b64encode(code_challenge).decode('utf-8')
code_challenge = code_challenge.replace('=', '')
```

**Comment by csy08** [comment]
Keen to see this in place too.
