### ISSUE TITLE
Authority port is not supported.

### ISSUE THREAD

**Issue by skyskitter** [AzureAD/microsoft-authentication-library-for-python#259]
**Describe the bug**
Authority port is not supported, always using default 443 port.

**To Reproduce**
Always reproduce when authority contains port.

**Steps to reproduce the behavior:**

Pass an authority with port

**What you see instead**
It is trying to connect to the 443 instead of the port passed in

**The MSAL Python version you are using**
All.

**Additional context**
A solution: use authority.netloc instead of authority.hostname in canonicalize function in authority.py

**Comment by skyskitter** [comment]
This could be solved by a custom http client

**Comment by rayluo** [comment]
@skyskitter , can you tell us more on under what scenario your authority setting comes with a port (that is different than the default 443)?
