### ISSUE TITLE
Update default cache lookup logic in ConfidentialClientApplication

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-python#265]
- Client credential flow should by default look in the cache and try to use the cached access token. [Internal design document](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/1948)
- On-behalf-of flow should by default look in the cache and try to use the cached access token. [Internal design document](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/1980)

**Comment by chlowell** [comment]
@rayluo is this still relevant? I'm implementing OBO and wonder whether there are any gotchas or limitations in the current MSAL I should consider.

**Comment by rayluo** [comment]
For a different reason, and as a byproduct of #577, the first topic "client credential flow" is now changed to automatically look up tokens from cache.

The OBO flow remains unchanged, for now. [The current calling pattern still utilize `acquire_token_silent()`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.22.0/tests/test_e2e.py#L676-L689).
