### ISSUE TITLE
result json object can't be read by requests

### ISSUE THREAD

**Issue by cyberpescadito** [AzureAD/microsoft-authentication-library-for-python#278]
**Describe the bug**
Using client certificate auth sample, the header of the get request (line 70 in sample) trigger a json error. 

**To Reproduce**
1. Go to our [off-the-shelf samples](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample) and pick one that is closest to your usage scenario. You should not need to modify the sample.
2. Follow the description of the sample, typically at the beginning of it, to prepare a `config.json` containing your test configurations
3. Run such sample, typically by `python sample.py config.json`
4. See the error
5. In this bug report, tell us the sample you choose, paste the content of the config.json with your test setup (which you can choose to skip your credentials, and/or mail it to our developer's email).

**Expected behavior**
I expected the list of Microsoft ATP alerts as return of the GET request.

What you see instead**
Debug activated:
INFO:root:No suitable token exists in cache. Let's get a new one from AAD.
DEBUG:msal.oauth2cli.assertion:Regenerating new assertion
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /redacted/oauth2/v2.0/token HTTP/1.1" 200 1549
DEBUG:msal.token_cache:event={
    "client_id": "redacted",
    "data": {
        "claims": null,
        "scope": [
            "https://graph.microsoft.com/.default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://graph.microsoft.com/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/redacted/oauth2/v2.0/token"
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.securitycenter.windows.com:443
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myproxy'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
DEBUG:urllib3.connectionpool:https://api.securitycenter.windows.com:443 "GET /api/alerts HTTP/1.1" 401 0
Traceback (most recent call last):
  File "msal_cert_auth.py", line 44, in <module>
    headers={'Authorization': 'Bearer ' + result['access_token']},).json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**The MSAL Python version you are using**
Paste the output of this
`python -c "import msal; print(msal.__version__)"`
1.6.0

**Additional context**
I added verify=False in the headers, that's why i got ssl warnings.

**Comment by rayluo** [comment]
When the sample runs to [its line 70](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.6.0/sample/confidential_client_certificate_sample.py#L70), a token has already been successfully acquired. The error you saw happened when our sample was trying to do JSON-decode to YOUR api response. My guess is your api, `https://api.securitycenter.windows.com/api/alerts`, does not return JSON-format data.

Which reminds us that, we would probably want to change all our samples to remove the assumption that those API calls would return JSON. We can make this change to our samples, but still, it is your journey to continue working with your API now. :-)

**Comment by cyberpescadito** [comment]
Crystal clear, thanks for your lights ! Will dig into it 🙂

**Comment by cyberpescadito** [comment]
well, i sleeped since, and with fresh mind I would say the issue is more about this line in my log:

DEBUG:urllib3.connectionpool:https://api.securitycenter.windows.com:443 "GET /api/alerts HTTP/1.1" 401 0

It's strange because the account I use got the permissions required to read the alerts in ATP:
![image](https://user-images.githubusercontent.com/32546144/100205341-4857fd00-2f05-11eb-9f7a-f50422d2bc26.png)

**Comment by rayluo** [comment]
(Replied within 8 minutes! My new record!)

Well, I'm going to sleep after an exhausting debugging session (for a different issue elsewhere).

You can change that line 70 from `.json()` to `.text`, so that you will see the raw response, which might have some clue. I do not otherwise have a clue right now on how that API should be configured.

**Comment by rayluo** [comment]
Closing this issue here, as it is not really relevant to this library. Feel free to ask [onboarding questions on StackOverflow with proper tags](https://stackoverflow.com/search?q=%5Bmsal%5D+and+%5Bpython%5D+or+%5Badal%5D+and+%5Bpython%5D) so that our dedicated team members would notice them.
