### ISSUE TITLE
getaccounts by username not getting user token

### ISSUE THREAD

**Issue by AlmogBentz** [AzureAD/microsoft-authentication-library-for-python#281]
**Describe the bug**
Using get accounts fynction in confidentialclientapp to get the right account for a user impersonation token, I am using the users unique id. It seems from the token cache data that the only email saved is the preferred_username which in some cases is different.

**To Reproduce**
Create a user with different unique_id and preferred_username. Try to get account with get_accounts function with unique_id.

**Expected behavior**
Since the only immutable id for a user is object_id, how about an option to send object_id to get_accounts function? This way there is no place for mishaps, or staleness in account identifier.

**What you see instead**
More than one field in id token that is interpreted as username/email and can change but still be cached.

**The MSAL Python version you are using**
1.6

**Comment by rayluo** [comment]
Welcome back, @AlmogBentz !

I'm not aware we expose a `unique_id` or `object_id` field. Did you mean the end user's email address? But even the email address is not necessarily immutable. So, that may not be the droid you are looking for.

Let's start from the scenarios first.

The `get_accounts(...)` API was initially designed to surface ALL accounts previously signed in with your app. Those accounts can then be fed to some sort of Account Picker UI widget, thus the assumption here is the end user would recognize their `username` (which usually came from their `preferred_username`), regardless of whether that name is in an email form or a "FirstName LastName" form.

If, on the other hand, your app is implemented to always operate in a single account mode. You may choose to call `get_accounts(...)` and when it returns one account, the app always proceeds with that account and call `acquire_token_silent(...)`. This way, you do not really need some unique thing to filter among accounts.

If you have different usage scenario than above, please let us know.

**Comment by AlmogBentz** [comment]
Hey :)
We are using msal in a multi tenant production environment were we have
multiple users per tenant. Our tokens were cached per tenant.
So the situation is that I could have multiple accounts in msal token cache
when a user wants to see some data from another source.
At that point we may have several users accounts(from the same tenant) in
our cache.

We dont involve the client-side in the whole user impersonation flow
because at that point we already have the user token cached.

So when I saw I can send username to get_accounts I thought this was a
specific claim from the id token. And I used the unique_id claim. In PPE
environment this seemed to work and looking in the token cache there was a
username field.

When moving to production, this works for the majority of users, but not
all. And with a specific user that I saw this doesnt work for there was no
username in the token-cache but there was a preferred_username field.

My assumption was that in this case the username I send (based on id token
unique_id field) is not the same as the one msal uses for choising the
account.

So in my case the thought was to use the users object_id to get the correct
account.

I hope this clears up my case (sorry for not being very clear before)

**Comment by rayluo** [comment]
> My assumption was that in this case the username I send (based on id token `unique_id` field) is not the same as the one msal uses for choosing the account.

[MSAL computes the account's `username` field based on some human-readable claims from id token](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.6.0/msal/token_cache.py#L182-L184), but `unique_id` is not one of them. In fact, an ID token does not usually have a `unique_id` field (see my example below). So, if you use the same source as username filter, MSAL's `get_accounts()` would work. If you configured your tenant to issue a `unique_id` field, MSAL won't be aware of it.

```
{'aio': 'ATQAy/8RAAAAQhjOoauJRZREVWc619EKbm5qxJTeEATlTEKcw97uDJSlU9E2v8zpw1/qS9uJ352J',
 'aud': '4b0db8c2-9f26-4417-8bde-3f0e3656f8e0',
 'exp': 1607127434,
 'iat': 1607123534,
 'iss': 'https://login.microsoftonline.com/f645ad92-e38d-4d1a-b510-d1b09a74a8ca/v2.0',
 'name': 'Cloud IDLAB Basic User 1',
 'nbf': 1607123534,
 'nonce': 'a886936e5e5d32cd7be5e215a01d8d39cc94847abc8b968c4927e645b7f48627',
 'oid': '597f86cd-13f3-44c0-bece-a1e77ba43228',
 'preferred_username': 'idlab1@msidlab4.onmicrosoft.com',
 'rh': 'I',
 'sub': 'YWrLb2etOFEQTYHmhlJr8vkr1sPrZ9YlS9us9h_zOx8',
 'tid': 'f645ad92-e38d-4d1a-b510-d1b09a74a8ca',
 'uti': 'Tk5LbMrE6k2u6lB1BKANAA',
 'ver': '2.0'}
```

Does the info above help on your "get_accounts() by username" question?

By the way:
* If YOUR app need a unique id for an end user for other-than-MSAL purpose, you may consider use the `sub` claim, which is defined as unique in Open ID Connect specs.
* Historically, MSAL's token cache design optimizes for desktop apps, which generally serves just one end user and their a few dozen tokens. When using MSAL in a backend web app, our [web app sample](https://github.com/Azure-Samples/ms-identity-python-webapp) manages to reuse the same small cache design, by partitioning into a "one cache per user" pattern. You mentioned your app is using a "(one?) cache per tenant" approach. I'd like to know how many tokens are stored in your cache. (You can reach me at my email for further discussion on this.)

**Comment by henrik-me** [comment]
@rayluo : Is there still an open discussion on this via email? Can this be concluded and closed or turned into a feature request?

**Comment by rayluo** [comment]
Summary so far: filtering accounts by an id token's oid is not currently supported by any MSAL. Almog has been working on adjusting her token cache model (from cache per tenant to cache per user). We will see how that goes. Almog can ping us again if encountering any difficulty. Closing this for now.
