### ISSUE TITLE
Import webbrowser only when necessary

### ISSUE THREAD

**Issue by jefferyto** [AzureAD/microsoft-authentication-library-for-python#287]
Hello :wave: I'm one of the Python maintainers for the OpenWrt packages feed. We have a user who wrote a script using MSAL and encountered an import error for `webbrowser` when run on their device (openwrt/packages#14198).

While the `webbrowser` module is part of the Python standard library, we don't ship `webbrowser` in our Python package to save disk space. AFAIK there also is no web browser package available for OpenWrt.

I see that `webbrowser` is only used in one place ([`_browse()`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/210c273a1101f36dc699408aa9265518844d3e6e/msal/oauth2cli/authcode.py#L37) in `msal/oauth2cli/authcode.py`). Would you be willing to accept a PR to move the `import webbrowser` statement into `_browse()`? This should fix the import error for the user (their script is non-interactive and does not need to open a browser) and allow our Python package to continue to not ship the `webbrowser` module.

**Comment by rayluo** [comment]
@jefferyto Thanks for bringing this to our attention. Will that PR work?
