### ISSUE TITLE
Validate Authorization token using msal

### ISSUE THREAD

**Issue by gudipudipradeep** [AzureAD/microsoft-authentication-library-for-python#289]
Please some one guide me which function I can use from msal to validate the Authorization token.
I have 
CLIENT_ID
CLIENT_SECRET
AUTHORITY

Please guide me which function will help for validation the token.

**Comment by aron89682** [comment]
I would also be interested in this.

**Comment by rayluo** [comment]
This is duplicate to #147 

By the way, @aron89682 , were you the person who send me email 2 days ago? My reply did not go through, the error message was "aron89682 wasn't found at gmail.com". Regardless, please create your new topic in that web app sample repo, and I'll address it there.

**Comment by aron89682** [comment]
@rayluo that was me and that's a strange error.  I'll create it there.  Thanks!

**Comment by rayluo** [comment]
Closing as a duplicate. Please subscribe and add ThumbUp emoji in the other issue.
