### ISSUE TITLE
Make msal compatible with PyJWT 2.x

### ISSUE THREAD

**Issue by reederz** [AzureAD/microsoft-authentication-library-for-python#293]
PyJWT version 2 came out. Can you make msal compatible with it? My project is using PyJWT, and I'd like to update it, but msal dependency prevents me from doing that: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/setup.py#L76 .

**Comment by henrik-me** [comment]
@rayluo to help investigate.
