### ISSUE TITLE
Can I use this library to access on-premises Dynamics CRM?

### ISSUE THREAD

**Issue by avioli** [AzureAD/microsoft-authentication-library-for-python#302]
I've got a client who wants our python app to create contacts in their on-premises Microsoft Dynamics CRM.

Can I use this library to get access to that?

**Comment by rayluo** [comment]
Probably yes. You'd need to find out what scope the Dynamics CRM would expect. I did not previously use Dynamics CRM before, so I do know that scope. @navyasric @idg-sam do you have an idea?

**Comment by avioli** [comment]
I'm guessing @navyasric @idg-sam don't have an idea?

**Comment by rayluo** [comment]
Hmm, perhaps they haven't used that product either. Is it possible that you can find out that info from Dynamics CRM's docs etc.?

MSAL is pretty close to a standard OAuth2 library, plus some Microsoft extra features. If a service or product is designed to be compliant to OAuth2, it should work. But then it is the service/product who decides what scope they registered.
