### ISSUE TITLE
1.9.0 release

### ISSUE THREAD

**Issue by rez10191** [AzureAD/microsoft-authentication-library-for-python#308]
Hello,

I wanted to inquire about when a `1.9.0` release might be made available.  Specifically, I'm interested in the functionality provided by https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/293 which allows compatibility with `pyjwt>=2.0.0` which is required by a project that I'm attempting to integrate with the Azure SDK.

Thanks for all your work on this project!

**Comment by rayluo** [comment]
> I wanted to inquire about when a 1.9.0 release might be made available

How about, [now](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/309)? :-)   #AnsweringGithubIssuesInStyle

**Comment by rez10191** [comment]
Awesome, thanks @rayluo !
