### ISSUE TITLE
ConfidentialClientApplication.acquire_token_for_client(scope) returning token with no role/scope

### ISSUE THREAD

**Issue by 0xUnicorn** [AzureAD/microsoft-authentication-library-for-python#324]
**Describe the bug**
When requesting a token using the "acquire_token_for_client(scope)" I get back a token without any scope/role. 
Neither of the following scopes works: 
1. ["https://graph.microsoft.com/.default"]
2. ["https://graph.microsoft.com/Directory.ReadWrite.All"]
3. ["Directory.ReadWrite.All"] 

No. 1 returns a token without a scope/role when running it through [jwt.ms](https://jwt.ms)
No. 2 & 3 fails with error: "invalid_scope", ""AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/Directory.ReadWrite.All is not valid."

**To Reproduce**
1. Register an application in AzureAD with API Permissions "Delegated - Directory.ReadWrite.All - Grant Admin Consent"
2. Generate a "ClientSecret" for the application.
3. Run the following script

`import msal

SCOPE = ["https://graph.microsoft.com/.default"]
CLIENT_ID = "1XXXXXXX"
CLIENT_SECRET = "2XXXXXXXXXX"
TENANT_ID = "3XXXXXXXXX"
AUTHORITY = f"https://login.microsoftonline.com/{TENANT_ID}"

application = msal.ConfidentialClientApplication(
            CLIENT_ID, authority=AUTHORITY,
            client_credential=CLIENT_SECRET)

response = application.acquire_token_for_client(SCOPE)

print(response)`

4. Copy access_token to [jwt.ms](https://jwt.ms) and verify the missing scope/role.

**Expected behavior**
A token containing the requested roles/scope.
![Screenshot from 2021-03-11 17-04-35](https://user-images.githubusercontent.com/17219001/110816697-df19b100-828b-11eb-978d-b168a8dcda61.png)

**What you see instead**
No scope/roles.
![Screenshot from 2021-03-11 16-51-22](https://user-images.githubusercontent.com/17219001/110815149-7d0c7c00-828a-11eb-81b7-ac8ebaf9829e.png)

**The MSAL Python version you are using**
msal version 1.10.0

**Additional context**
I have an app with some different permissions
![Screenshot from 2021-03-11 17-05-48](https://user-images.githubusercontent.com/17219001/110816892-0bcdc880-828c-11eb-9008-3d9fc8af1775.png)
If I request a token with `SCOPE = ["https://graph.microsoft.com/.default"]` and the belonging Client_id and Client_secret, I get a token like posted in **Expected behavior** but it's not possible to get all of the other roles added to the App within the token no matter what SCOPE I use.

**Comment by rayluo** [comment]
> If I request a token with `SCOPE = ["https://graph.microsoft.com/.default"]` and the belonging Client_id and Client_secret, I get a token like posted in Expected behavior

That would mean the `acquire_token_for_client()` works as expected to get you the Application permission. For the other 2 Delegated permissions, you would need to use other `acquire_token_by_...()` methods to obtain the user consent. See "Application permission VS Delegated permission" [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#permission-types).

**Comment by 0xUnicorn** [comment]
@rayluo thank you very much for your reply

Sorry, that's my bad, I didn't pay attention to the different API Permissions in the two categories.

I also found this note, can you confirm if that means requesting a subset of the consented Application permissions from my code isn't possible. 
So my code will retrieve all of the consented application permissions or else I would need different applications with different consented Application permissions?

![Screenshot from 2021-03-11 19-00-01](https://user-images.githubusercontent.com/17219001/110832872-14c69600-829c-11eb-8fae-21a7323bfbdc.png)

**Comment by rayluo** [comment]
I'm not entirely sure, but you can first try combining those scopes in same "acquire_token_by...()" call. If that does not work, you can at least use different `acquire_token_for_client(...)` and `acquire_token_by_...()` while using the same app. You shouldn't need to register 2 apps for that.

Let us know how it goes. :-)

**Comment by 0xUnicorn** [comment]
Hey Ray, thanks for your suggestions, you're the man!

`acquire_token_by_auth_code_flow` is a method belonging to `ClientApplication` instead of `ConfidentialClientApplication` but calling it from an instance of `ClientApplication` gives me the same error. I found it declared in `application.py`. 

```
response2 = application.acquire_token_by_auth_code_flow(SCOPE)
AttributeError: 'ConfidentialClientApplication' object has no attribute 'acquire_token_by_auth_code_flow'

response2 = application.acquire_token_by_auth_code_flow(SCOPE)
AttributeError: 'ClientApplication' object has no attribute 'acquire_token_by_auth_code_flow'
```

Just for making sure what I need is explained thoroughly I'll give an example.

#Service1 - Create global administrators
#Service2 - Create Microsoft365 groups
#Service3 - Create widgets for SecurityEvents.

Registered application "foo" has the following permissions all with "Admin consent granted" in the tenant:
- Directory.ReadWrite.All (Type: Application)
- RoleManagement.ReadWrite.Directory (Type: Application)
- SecurityEvents.Read.All (Type: Application)

Service1 needs permissions "Directory.ReadWrite.All" and "RoleManagement.ReadWrite.Directory"
Service2 needs permissions "Directory.ReadWrite.All"
Service3 needs permissions "SercurityEvents.Read.All"

All 3 services are independent containers requesting a token individually from the same registered application.

If one of the services requests a token using `/.default` it will get alle 3 permissions. So I would like to only request the needed permissions for every service, that was my definition of a "subset".

Thank you for your time! 👍

**Comment by rayluo** [comment]
Thanks. And you are the Unicorn! :-)

> ```python
> response2 = application.acquire_token_by_auth_code_flow(SCOPE)
> AttributeError: 'ConfidentialClientApplication' object has no attribute 'acquire_token_by_auth_code_flow'
>
> response2 = application.acquire_token_by_auth_code_flow(SCOPE)
> AttributeError: 'ClientApplication' object has no attribute 'acquire_token_by_auth_code_flow'
> ```

That is strange, though. Are you sure your program does not contain any typo? Here is what I got.

```python
>>> import msal
>>> app = msal.ConfidentialClientApplication("client_id", "my_secret")
>>> app.acquire_token_by_auth_code_flow
<bound method ClientApplication.acquire_token_by_auth_code_flow of <msal.application.ConfidentialClientApplication object at 0x7f93e8465e48>>
```

So at leat that method does exist, as you also independently found out.

```python
>>> app.acquire_token_by_auth_code_flow(["scope1"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: acquire_token_by_auth_code_flow() missing 1 required positional argument: 'auth_response'
```
That method call was trying to mimic your calling pattern. I still did not encounter an `AttributeError`. I don't know why your test would encounter that, but it is hard to tell. I think you would need to review your python script.

The `TypeError` in my test was expected, though, because you were not calling acquire_token_with_auth_code_flow() with [the right way](https://msal-python.readthedocs.io/en/latest/#confidentialclientapplication).

**Comment by 6peterlu** [comment]
I'm getting the same issue as @0xUnicorn, except that when i use `scopes=[".default"]` or equivalent, I still get no scopes and roles. Any ideas on what might be going wrong here? Here's how I'm calling it:
```
  auth_app = msal.ConfidentialClientApplication(
    os.environ["MS_CLIENT_ID"],
    authority=f"https://login.microsoftonline.com/{tenant_id}",
    client_credential=os.environ["MS_SECRET"]
  )
  result = auth_app.acquire_token_for_client(SCOPES)
```
cc @rayluo
