### ISSUE TITLE
Hi - I'm coming back! why I don't see refresh token or user information? 🤣 

### ISSUE THREAD

**Issue by dudil** [AzureAD/microsoft-authentication-library-for-python#328]
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/d3b772c706f900ae0b06505fdba236501004a3dd/msal/application.py#L34-L37

Just kidding guys, thank you for your hard work! Appreciated!

**Comment by rayluo** [comment]
Aha, when I [wrote that line 3 years ago](https://github.com/AzureAD/microsoft-authentication-library-for-python/blame/d3b772c706f900ae0b06505fdba236501004a3dd/msal/application.py#L34-L37), I did not anticipate our customers would notice that. But @dudil you clearly did your homework.

And, thank you for your kind words, and your sense of humour. It took me a minute to understand. You made my day! :-)  :rofl:

**Comment by jennyf19** [comment]
@dudil 🏆 for you! Best issue I've seen in a LONG time! 😹
