### ISSUE TITLE
Validating @azure/msal-react token sent from front-end to Django/DRF back-end

### ISSUE THREAD

**Issue by cheslijones** [AzureAD/microsoft-authentication-library-for-python#330]
I'm using [`@azure/msal-react`](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) to get `access_token`, `id_token`, and `email` client-side.

From what I gather, I need to send these to my Django/DRF back-end to have them validated there as well. Basically, do the `access_token` and `id_token` really belong to the user with this email? If they do, see if the user is in the database and issue them a JWT. If they aren't create a record for them, and send them a JWT.

The server-side validation is what I'm not sure about.

- I've been scanning through [`microsoft-authentication-library-for-python`](
https://github.com/AzureAD/microsoft-authentication-library-for-python) and isn't entirely clear to me if I need to use it for this purpose or...
- Is there some Microsoft end-point I'm not currently aware of that I can send these tokens to from Django/DRF to verify they are valid and who the user is.

Can you provide clarification on this?

**Comment by idg-sam** [comment]
Hi @cheslijones ,

Great question. MSAL Python is a token acquisition and caching library, and not a token validation library. Generally, what you'd need to do is send the `access_token` (one that was issued specifically to access your application) to your back-end service in a header (`Authorize: Bearer {access-token}`) along with your request.

It's then the responsibility of the BE service to validate the token. It must verify at least the following assertions about the access token:
1. that its `aud` (audience) claim is that of the backend service.
2. that its `iss` (issuer) claim is Azure AD or one of its aliases.
3. that it signature confirms it is signed by valid Azure AD signing keys (or custom signing keys if your app has configured it as such).
4. That it is currently valid (not yet past its `exp` claim, not before its `nbf` claim).

Next, you must assert any other claim(s) that are specific to your app and require custom validation (e.g., scopes)

You can [start here](https://docs.microsoft.com/azure/active-directory/develop/access-tokens#validating-tokens) for a guide on how to validate access tokens from your back-end service. 

We don't (yet) have samples for how to validate Azure AD access tokens in Django back-end web services, but please stay tuned!

**Comment by shreyanshjain1605** [comment]
What will be the code in Django(Python) to validate token? Please share if u have reference @idg-sam
