### ISSUE TITLE
When is your next release?

### ISSUE THREAD

**Issue by cai-liu** [AzureAD/microsoft-authentication-library-for-python#347]
Hi Microsoft developers,

**Describe the bug**
When do you plan to release the latest changes on username/password sample?

**To Reproduce**
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/username_password_sample.py

I am a devops engineer and we are implementing some automated script in python to interact with SharePoint and other M365 apps. Due to our current infrastructure, we have to find a way to authenticate to o365 tenant in a non-interactive way in python.

Both Graphapi Application permission (site.ReadWrite.all) and Public client flow option of Azure app authentication are not approved by our security team.

So far I only found your latest change to the username_password_sample meets our requirement. Could you let me know that whether/when do you plan to release the changes you made on the dev branch of this repository.

Best regards,
Cai

**Comment by rayluo** [comment]
How about, [now](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.11.0)?
