### ISSUE TITLE
Can you bypass the “select account” prompt when logging out?

### ISSUE THREAD

**Issue by reubano** [AzureAD/microsoft-authentication-library-for-python#366]
**Describe the bug**

I can't seem to bypass the “select account” prompt when logging out. My thought was to implement ~[Single Sign-Out](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-out-saml-protocol)~ [Single Sign-Out](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#single-sign-out) but I'm not sure if that is either feasible or the proper solution. (Edited to replace link to SAML protocol docs w OIDC protocol docs.)

**To Reproduce**

[Sample App](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/app.py#L47)

**Expected behavior**

I should be able to force a user to logout without the app prompting them to select an account to log out of.

**What you see instead**

Users gets this prompt and isn't logged out of the app until they consent.

<img width="453" alt="Screen Shot 2021-05-19 at 12 10 35" src="https://user-images.githubusercontent.com/157864/118876637-1b344800-b8b3-11eb-9ef1-2acad6ad749f.png">

**The MSAL Python version you are using**

1.9.0

**Additional context**

`auth.py`

```python
@blueprint.route("/logout")
@login_required
def logout():
    redirect_uri = url_for("Authentication.login", _external=True)

    try:
        forced = request.args.get("force").lower() == "true"
    except AttributeError:
        forced = False

    session.clear()

    if forced:
        # Normal logout route requires user to select which account they want to log out of
        cache = _load_cache() 
        cca = _build_msal_app(cache=cache)
        accounts = cca.get_accounts()

        if accounts:
            cca.remove_account(accounts[0])

        response = redirect(redirect_uri)
    else:
        # Also logout from your tenant's web session
        response = redirect(
            "{AUTHORITY}/oauth2/v2.0/logout?post_logout_redirect_uri={0}".format(
                redirect_uri, **authentication
            )
        )

    return response
```

CR #94, CR #258

**Comment by reubano** [comment]
I also tried deleting the cookies and that didn't work either

```python
    if forced:
        …
        response = redirect(redirect_uri)
        response.delete_cookie(".AspNet.CookiesC1", domain="app.powerbi.com")
        response.delete_cookie(".AspNet.CookiesC2", domain="app.powerbi.com")
        response.delete_cookie(".AspNet.Cookies", domain="app.powerbi.com")
        response.delete_cookie("ai_session", domain="app.powerbi.com")
        response.delete_cookie("ai_user", domain="app.powerbi.com")
        response.delete_cookie("ARRAffinitySameSite", domain="app.powerbi.com")
        response.delete_cookie("ARRAffinity", domain="app.powerbi.com")
        response.delete_cookie("ASP.NET_SessionId", domain="app.powerbi.com")
        response.delete_cookie("ClusterUri", domain="app.powerbi.com")
        response.delete_cookie("LoginErrorReattemptCount", domain="app.powerbi.com")
        response.delete_cookie("PowerBISignedInFlag", domain="app.powerbi.com")
        response.delete_cookie("PowerBIUserSignedUp", domain="app.powerbi.com")
        response.delete_cookie("PreferredLanguage", domain="app.powerbi.com")
        response.delete_cookie("WFESessionId", domain="app.powerbi.com")
```

**Comment by rayluo** [comment]
I happen to find [this stackoverflow question](https://stackoverflow.com/questions/56700229/is-there-a-way-to-avoid-the-select-account-prompt-while-logging-out-of-microso) suggesting that it is not currently possible to avoid that account selection User Experience. That is probably the status quo. We can come back to update this answer when/if the situation changes.

**Comment by reubano** [comment]
@rayluo I think [the article](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-out-saml-protocol) I linked to above supersedes that SO answer. Here's the [.Net sample app](https://github.com/Azure-Samples/active-directory-dotnet-web-single-sign-out).

**Comment by rayluo** [comment]
The [article you referenced to is for SAML2 protocal](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-out-saml-protocol). However, [the .Net sample app you referred to](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-6-SignOut#single-sign-out), as well as [the MSAL Python web app sample that you currently use](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/app.py#L51), are based on the same [OIDC sign out](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#single-sign-out). I believe that .Net sample app would behave the same as your current Python sample web app. Please let us know if that is not the case.

**Comment by reubano** [comment]
Hmmm, good point about the protocol @rayluo. Unfortunately, I'm not a .Net dev so haven't tried that sample app. However, they have a [Single Sign-Out](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-6-SignOut#single-sign-out) section which seems like it should do what we need.

Otherwise, are there any workarounds? I thought clearing the cookies would work, but I'm either not doing that correctly or there is something else more involved needed. My idea in the example above was to bypass the logout prompt by redirecting to the login page (instead of `/oauth2/v2.0/logout`) with a cleared session. But the app just happily reauthenticates on its own...

I figured there should be a way to remove all tokens and redirect to the login page to prompt the user to login (since there won't be any cached token to reauthenticate automatically).

**Comment by rayluo** [comment]
Your web app reauthenticates on its own, because it relies on the upstream Microsoft identity platform's login session, which you can only log out by visiting its logout URL, at that point the account selector UI kicks in. You could theoretically remove some cookies to void that session, but then you are essentially reverse-engineering the Microsoft identity platform's session management. We won't recommend you to go down that route.

Currently, our response remains the same as [the first response of this conversation](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/366#issuecomment-844487214).

**Comment by jiasli** [comment]
I can't repro it (as of 2021-05-24). After logging in at `/authorize` and then `/logout`, it automatically logs out the user:

![image](https://user-images.githubusercontent.com/4003950/119287398-05d76900-bc79-11eb-91ce-db85512f81d8.png)

**Comment by reubano** [comment]
@jiasli thanks for that data point! So either something is funky with my account, or the modifications I made to the sample app altered the behavior. What does your login screen look like? Here's mine.

<img width="455" alt="Screen Shot 2021-05-24 at 10 49 02" src="https://user-images.githubusercontent.com/157864/119373307-e1ca5680-bc7d-11eb-915d-0b5f813f405c.png">

**Comment by rayluo** [comment]
Thanks for @jiasli 's input. I also tested it just now, and realized that it depends on the account type. If the signed-in user is a Work and School account (something like janedoe@contoso.com), there will be an account selector during sign out. If the signed-in user is an Microsoft Account (something like johndoe@outlook.com), the logout process still show the account selector page but it quickly automatically proceeds to a successfully-signed-out page.

**Comment by reubano** [comment]
I can confirm I'm using a work account.

**Comment by jiasli** [comment]
Oh! I noticed I was logging out using AAD 1.0 at https://login.microsoftonline.com/common/oauth2/logout and it logs me out automatically.

But on AAD 2.0 https://login.microsoftonline.com/organizations/oauth2/v2.0/logout, it always shows the account selector page for both account types:

Work and School account me@microsoft.com

![image](https://user-images.githubusercontent.com/4003950/119431646-86639b80-bd45-11eb-9839-e27ef1e9878b.png)

Microsoft account me@outlook.com

![image](https://user-images.githubusercontent.com/4003950/119431687-967b7b00-bd45-11eb-8168-fb68c0152095.png)

**Comment by reubano** [comment]
@jiasli, Yea I read about using the v1 API in the SO question. Looks like that's the only way until they fix the v2 API.

CR https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/490

**Comment by reubano** [comment]
This may deserve a to be sep issue, but since using the v1 API, I've noticed an odd behavior...

I setup an auto logout timer and it only works intermittently, e.g., actually logs the user out every 2 or 3 logout cycles. In the other cases, it just reloads the page.
