### ISSUE TITLE
Does msal support 2FA Authentication

### ISSUE THREAD

**Issue by AmitKulkarni9** [AzureAD/microsoft-authentication-library-for-python#377]
Can we acquire a token for 2FA authentication

**Comment by rayluo** [comment]
You bet. Some APIs (auth code flow and interactive auth) naturally support 2FA during the interaction. It is more about what your app is, and what pattern it would use. You can probably find some sample from this "[map](https://github.com/AzureAD/microsoft-authentication-library-for-python#scenarios-supported)".

**Comment by AmitKulkarni9** [comment]
Thanks Ray.
Can we get the token for 2MFA user having Password and then enter OTP without user interaction through MSAL ? End-to-end automation.

Regards,
Amit

**Comment by rayluo** [comment]
In a sense, the "Desktop app" in the "[map](https://github.com/AzureAD/microsoft-authentication-library-for-python#scenarios-supported)" is guiding user to sign in through browser, during which process the end user could be prompted to input password and complete 2FA.

Perhaps you can try first choose your app's scenario from the map, and then we discuss whether/how the corresponding sample does (not?) meet your requirement.
