### ISSUE TITLE
Token is never found in token cache

### ISSUE THREAD

**Issue by rodneyjoyce** [AzureAD/microsoft-authentication-library-for-python#42]
Hi, I'm trying this library and have noticed that my token is never persisted to the cache it would seem:

The acquire_token_silent never finds a token in the cache but documentation implies that acquire_token_for_client would update the cache when it receives a result.

Is this implemented?  Thanks

```
authority_host_uri = 'https://login.microsoftonline.com'
authority_uri = authority_host_uri + '/' + tenantId
resourceUri = ["https://graph.microsoft.com/.default"]  #V2

app = ConfidentialClientApplication(clientId, client_credential=clientSecret, authority=authority_uri)

token = app.acquire_token_silent(resourceUri, account=None)
print("TOKEN CACHE: {0}" .format(token))  
  
if not token:
  print("getting new token")
  token = app.acquire_token_for_client(scopes=resourceUri)
  
if "access_token" in token:
  print(token)
else:
  print(result.get("error"))
  print(result.get("error_description"))
  print(result.get("correlation_id")) 
```

**Comment by rayluo** [comment]
Thanks for your interest in trying out MSAL Python! So your code snippet looks very similar to our sample but missing [these lines](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0.3.1/sample/confidential_client_secret_sample.py#L38-L40). Would that help?

**Comment by rodneyjoyce** [comment]
Yes, that was it, thank you. I added this and now it is finding the token in the cache:

cache = SerializableTokenCache()
...
app = ConfidentialClientApplication(clientId, client_credential=clientSecret, authority=authority_uri, token_cache=cache)
