### ISSUE TITLE
Support auth code flow in docker container

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#422]
## Goal

Support we want to support auth code flow in docker container, as opposed to https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/421.

## Solution 1: `--net=host`

`--net=host` is used to put the container **directly** in the `host` network. Unfortunately, as mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/309#discussion_r731469989, `--net=host` doesn't work on platforms other than Linux, like Windows or MacOS:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0deba2e88a9595986282b14ce03a57bc9dc0539c/msal/oauth2cli/authcode.py#L246

So we have to use other approaches.

## Solution 2: `--publish , -p`

I tried to use `--publish , -p` to expose/map certain port like `8400` to the hosting Windows:

```
docker run -it -p 8400:8400 -v d:/cli/azure-cli:/root/azure-cli python:3.9 bash
cd /root
python -m venv pyenv
. pyenv/bin/activate
pip install azdev
azdev setup -c azure-cli
```

However, after running `az login`, the browser fails with 

![image](https://user-images.githubusercontent.com/4003950/137849905-41353ec7-4e5f-4e29-84c2-88a2f4cd3e33.png)

```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

This is because `AuthCodeReceiver` only listens to `127.0.0.1`:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0deba2e88a9595986282b14ce03a57bc9dc0539c/msal/oauth2cli/authcode.py#L132

As the container runs in `bridge` network (`docker inspect <name>`), the IP address is actually

```
# hostname --ip-address
172.17.0.3
```

It fails because the IP doesn't match.

This can be cross-checked with

```
python -m http.server 8400 --bind 127.0.0.1
```

Now visiting http://127.0.0.1:8400 from the host shows the same error message.

But if we listen to all port:

```
python -m http.server 8400
```

http://127.0.0.1:8400 works as expected.

### Experiment

After changing https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0deba2e88a9595986282b14ce03a57bc9dc0539c/msal/oauth2cli/authcode.py#L132

to `""`, I can successfully do an auth code flow in a docker container!

**Comment by rayluo** [comment]
Yes, our goal is to facilitate using auth code flow even inside a docker container. MSAL's `acquire_token_interactive()` is specifically designed to allow that, so it is already doing its part. But then it is each different deployment scenario's challenge to somehow route the incoming auth code back to MSAL. The current unfortunate situation that the [`docker --net=host ...` is not (yet?) supported on Windows/Mac is a feature request for docker](https://github.com/docker/roadmap/issues/238) in its own right.

MSAL Python is even implemented in a way that it would be very easy to expose that `address` parameter. The question remains as how the calling app would know which IP address to be listened to. We need to investigate whether there is a way for an app running inside docker can reliably detect and choose an ip (such as 172.17.0.3) to use. Unless/until we make some breakthrough in that detection, we don't think MSAL's exposing that `address` parameter would make any real difference.

**Comment by tevino** [comment]
Having the exact situations here.

@jiasli @rayluo 
Is there a temporary workaround to make `acquire_token_interactive()` work in a docker container on macOS/Windows?

I would say that even if `--net=host` is supported on all platforms, an exposed `listen_address` from msal would be a more fine-grained solution than using a host network.

**Comment by rayluo** [comment]
> I would say that even if `--net=host` is supported on all platforms, an exposed `listen_address` from msal would be a more fine-grained solution than using a host network.

*If `--net=host` is supported on all platforms*, the current MSAL Python would already work out of the box, and there would be no need to expose `listen_address` from msal, not until we can articulate a *concrete* scenario. (In other words, we tend to expose a fine-grained parameter only if it can be justified by enabling a new scenario.)

In reality, `--net=host` might not be available on macOS or Windows anytime soon, so, yeah, MSAL Python is open to that `listen_address` idea. Assuming MSAL exposes that parameter, @jiasli, how does Azure CLI plan to utilize it? Is the end user expected to run something like "docker run ... -p 8400:8400 ..." and then "az login --listen-address 0.0.0.0 --port 8400" when running inside a container? The user experience seems suboptimal, I doubt how many users would know it, even after we change the [existing docs](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker#install-azure-cli-in-docker) to point out the different docker commands.

> Is there a temporary workaround to make `acquire_token_interactive()` work in a docker container on macOS/Windows?

For now, you would have to `az login --use-device-code`.

**Comment by jiasli** [comment]
> @jiasli, how does Azure CLI plan to utilize it? Is the end user expected to run something like "docker run ... -p 8400:8400 ..." and then "az login --listen-address 0.0.0.0 --port 8400" when running inside a container?

Yes. This is the solution I can think of, and indeed, it is suboptimal...

**Comment by tevino** [comment]
My scenario is doing automated testing in a docker container that requires authentication for SharePoint Online, no need to `az login`.

This is what I ended up doing with `msal==1.16.0`, for people who have the same need:

```python3
from unittest.mock import patch
import msal.oauth2cli

def overrite_addr(original_class, new_addr):
    orig_init = original_class.__init__
    # Make copy of original __init__, so we can call it without recursion

    def __init__(self, address, *args, **kws):
        port = address[1]
        orig_init(self, (new_addr, port), *args, **kws) # Call the original __init__

    original_class.__init__ = __init__ # Set the class' __init__ to the new one
    return original_class


with patch(target='msal.oauth2cli.authcode._AuthCodeHttpServer',
           new=overrite_addr(msal.oauth2cli.authcode._AuthCodeHttpServer, '0.0.0.0')):
    # This is necessary as long as:
    # 1. msal hard-coded 127.0.0.1 in its source, see: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/422
    # 2. We are in a docker container on non-Linux platform (so --net=host is not supported)
    result = app.acquire_token_interactive(scopes=scopes, port=REDIRECT_PORT)
```

**Comment by rayluo** [comment]
Thanks for sharing your usage, @tevino ! So, you did choose your specific port REDIRECT_PORT, and you did setup the port forwarding when you start your container "docker run ... -p xyz:xyz ...", didn't you?

Regardless, we will take a close look after holiday, and update this thread accordingly.

**Comment by tevino** [comment]
@rayluo That's exactly what I did, thanks for taking care of this scenario, and happy holiday! 🎉

**Comment by rayluo** [comment]
@enerdev2022, have you tried running MSAL's interactive sample inside your Docker which was running on Linux? If so, you should have already seen this [built-in hint](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.20.0/msal/oauth2cli/authcode.py#L268). Please let us know if that does not work.

**Comment by bgavrilMS** [comment]
This is a very old thread, marking as answered and will close. Please comment if it needs to be reopened.

**Comment by sam-mfb** [comment]
We had a need to do a similar thing--interactive auth from the CLI in a docker container using the host browser--and I ended up writing this utility to do it. 

https://github.com/sam-mfb/oauth2-forwarder

We use it with msal-node but it's platform agnostic. It basically uses the same conceptual approach that VS Code uses for managed containers, namely, using a tcp server/client connection to pass the needed info back and forth between host/container.

The downside is you need to have a small server instance running on your host. The upside is you don't really need to change anything about your app or docker configuration (other than setting the BROWSER env variable). 

Feel free to put questions/comments on the repo for the project.

**Comment by rayluo** [comment]
For posterity, the original feature request was achieved by these building blocks:

1. [MSAL Python 1.25](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.25.0)+ being capable to detect its running inside docker and automatically switched to listening on `0.0.0.0` instead of localhost.
2. When a browser is unavailable inside the container, MSAL (and Azure CLI) shall display the login URL inside the container. That URL is typically clickable when it is running inside a modern terminal, so, a browser on host will be triggered by just one click.
3. However, the app developer does need a setup to somehow relay the incoming http request back to the container. The most convenient way is to use `docker run ... --net=host`, providing that your docker host is on Linux. Otherwise, your app would have to specify a port beforehand by `acquire_token_interactive(..., port=1234)` and then setup the port forwarding when you start your container `docker run ... -p 1234:1234 ...`.

Now I'm marking this issue as a feature request and marking it as done.

**Comment by neurabluAI** [comment]
I solved this by using the device_flow and showing the link and user code from the response. An additional QR makes it accessible even from a second device easily. The suggestion posted by rayluo didnt work for me unfortunately / couldnt implement it correctly :/

**Comment by rayluo** [comment]
> I solved this by using the device_flow and showing the link and user code from the response. An additional QR makes it accessible even from a second device easily. The suggestion posted by rayluo didnt work for me unfortunately / couldnt implement it correctly :/

For the record, the 3rd step in my suggestion was derived from another github user's [successful story, posted also in a late December, 3 years ago](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/422#issuecomment-1000091421).

Device Flow approach can also work, but it is usually considered less user-friendly. Also, tokens received by Device Flow is just different, and may not always be accepted by a downstream service.

Anyway, the choice is yours.
