### ISSUE TITLE
MSAL can consider using lazy import for `request`, `jwt`

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#423]
**Describe the bug**

Importing MSAL is can cost ~300ms on Windows due to some heavy libraries like `request` and `jwt`: 

```
python -X importtime -c "import msal"  2>perf.log; tuna .\perf.log
```

![image](https://user-images.githubusercontent.com/4003950/137872368-a85b9753-f46b-4ffe-acdd-323815486c1b.png)

MSAL can consider using lazy import for these libraries so that importing MSAL can be lightweight. (Azure CLI lazily imports MSAL: https://github.com/Azure/azure-cli/pull/19898)

**Comment by rayluo** [comment]
@jiasli , your screenshot indicated that the `requests` and `jwt` combined for 2/3 of the msal import time. The PR above is able to remove those 2 parts from the tuna chart, however the overall import time was only cut short by 1/3, rather than 2/3. Still better than the current situation. :-/
