### ISSUE TITLE
Expecting access token to be JWT v2 but got v1

### ISSUE THREAD

**Issue by raqsilva** [AzureAD/microsoft-authentication-library-for-python#426]
Hello,

Background:
msal version = "1.15.0"
python version = "3.8.12"

Authority = "https://login.microsoftonline.com/{tenant_id}/v2.0"

I have changed my app manifest var `"accessTokenAcceptedVersion": 2`. 
My app is a confidential client application using default scopes and I'm getting my access token through `acquire_token_by_auth_code_flow` which gives me an access token v1 and id token v2.

How can I make sure I always get a v2 token?

Thanks,
Raquel

**Comment by rayluo** [comment]
Thanks for @hpsin 's hint, and glad to see @raqsilva figured it out. By the way, MSAL is currently a token acquisition library, so MSAL users do not normally need to care about the version of the obtained token. @raqsilva you were working on token validation? No wonder you created this topic. :-)  We do not currently have an offering on token validation in Python. We will mark this issue as answered here, and we will reference it in future when we work on token validation.
