### ISSUE TITLE
Make `http_client`'s `max_retries` configurable

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#432]
## Symptom

The one-time retry introduced by https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/326 seems to be insufficient:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/62752adbcc8700c9e5969cacdce64c23bb8802c8/msal/application.py#L423-L425

Transient `ConnectionError` can still makes MSAL fail: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/431

## Alternatives

Of course I can provide my HTTP client, but this seems too heavy for such as small parameter tweak.

**Comment by rayluo** [comment]
This issue was created when #431 was observed. Now we have addressed #431 in its corresponding PR, by providing clearer error message. End user will then make educated decision on manual retry when needed. So, there is less need for an app to automatically choose a max retries value.

Besides, `max_retries` is an http layer behavior. It does not really belong to the MSAL or OAuth2 layer. We choose to not make this change.

**Comment by jiasli** [comment]
I want to reopen this issue as https://github.com/Azure/azure-cli/pull/29452 is requesting managed identity authentication's retry to be configurable.

**Comment by doubleyewdee** [comment]
@jiasli yes, we'd appreciate being able to tune retries here (it looks like there's at least one retry which is better than what we have today already so that's excellent)

**Comment by rayluo** [comment]
> I want to reopen this issue as [Azure/azure-cli#29452](https://github.com/Azure/azure-cli/pull/29452) is requesting managed identity authentication's retry to be configurable.

Instead, please consider use a customized [`http_client`](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.http_client) with your own retry logic instead.

> (it looks like there's at least one retry which is better than what we have today already so that's excellent)

Note that the default retry-once behavior is only available in MSAL Python's non-Managed Identity code path. For [managed identity, the current API](https://msal-python.readthedocs.io/en/latest/#msal.ManagedIdentityClient) requires the caller to provide an `http_client` anyway.
