### ISSUE TITLE
Feature request: Provide the possibility to use a webview instead of the system browser.

### ISSUE THREAD

**Issue by CmdrRikr** [AzureAD/microsoft-authentication-library-for-python#438]
**Feature description**     
In the msal for C# it is possible to use a [embedded webview](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-web-browsers#enable-embedded-webviews-on-ios-and-android) instead   
of the system browser for sign in (at least for android and ios devices).   
   
It would be very useful to have this feature in the python libary too in order   
to provide more control over the signin window behavior.

**Comment by rayluo** [comment]
What platform are you referring to? Python is generally not used on Android and iOS devices.

If you mean to say Windows platform, it is true that MSAL for C# can still use an embedded webview. But then, what kind of "more control" do you have in mind? Can you elaborate? We would want to make sure we fully understand your expectation.

**Comment by CmdrRikr** [comment]
With more control I have in mind that I want the confirmation message to be separable from the login process. 
Currently this confirmation message is opened in a separate tab. Being able to inform about a successful login 
within my own application would be helpful or not show the message at all and instead fail if the login was not
successful. It would also be helpful to be able to close the confirmation message from within my application 
without closing the system browser.

**Comment by rayluo** [comment]
Thanks for explaining. By the way, what is the platform your app runs on? Is it a desktop GUI app or a command line script?

**Comment by CmdrRikr** [comment]
The app runs on Windows. Msal for python is used in a own library without a GUI. The app which uses this library has a GUI.

**Comment by rayluo** [comment]
[MSAL Python 1.25 supports using a broker](https://msal-python.readthedocs.io/en/latest/#publicclientapplication) which came with Windows 10+. That can accomplish what you need. You can refer to this [sample for interactive login](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/interactive_sample.py).
