### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-python#466]
Now we have different API/behaviors for customers to disable authority validation and instance discovery.

Please sync across languages to provide consistent ones.

This is important because JEDI scenarios are blocked by current behavior.

**Comment by rayluo** [comment]
This has been addressed in #496, and released in [MSAL 1.19+](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.19.0).
