### ISSUE TITLE
Fuzzing integration by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [AzureAD/microsoft-authentication-library-for-python#486]
Hi,

I was wondering if you would like to integrate continuous fuzzing by way of OSS-Fuzz? In this PR https://github.com/google/oss-fuzz/pull/7754 we do exactly this, namely created the necessary logic from an OSS-Fuzz perspective.

Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

If you would like to integrate, the only thing I need is as list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by rayluo** [comment]
> If you would like to integrate, the only thing I need is as list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

Are you talking about adding the email(s) to [here](https://github.com/google/oss-fuzz/pull/7754/files#diff-80ba2d3bea74e616ca4fcf0c0a974e09dfa7b7eb96ba01f0db98e832849c09aeR8-R11)? Sure. Go ahead to use my email, which you can find in my profile and/or my commits. By the way, are those existing emails in your current PR intended to be there?

When OSS-Fuzz finds bugs in the test subject (MSAL in this case), do we as the project maintainers need to periodically check your [OSS-Fuzz bug list](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=-status%3AWontFix%2CDuplicate%20-component%3AInfra&can=1)? Will OSS-Fuzz proactively send notifications to my email? Or, even better, can OSS-Fuzz create github issues to the corresponding upstream OSS projects? That way would be more reliable in the long term, after the initial individuals eventually moving out of the project.

I have some other specific questions on OSS-Fuzz. I'll leave comments into your PR there.

**Comment by DavidKorczynski** [comment]
> Are you talking about adding the email(s) to [here](https://github.com/google/oss-fuzz/pull/7754/files#diff-80ba2d3bea74e616ca4fcf0c0a974e09dfa7b7eb96ba01f0db98e832849c09aeR8-R11)? Sure. Go ahead to use my email, which you can find in my profile and/or my commits. By the way, are those existing emails in your current PR intended to be there?
> 
Thanks Ray, will do! The existing emails are there just for us to help with the integration, for example, there may be something in the set up that breaks or similar when the fuzzers start running to continuously. Am happy to remove if you prefer but it's for us to assist in case of any mishappeninngs!

> When OSS-Fuzz finds bugs in the test subject (MSAL in this case), do we as the project maintainers need to periodically check your [OSS-Fuzz bug list](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=-status%3AWontFix%2CDuplicate%20-component%3AInfra&can=1)? Will OSS-Fuzz proactively send notifications to my email? Or, even better, can OSS-Fuzz create github issues to the corresponding upstream OSS projects? That way would be more reliable in the long term, after the initial individuals eventually moving out of the project.
> 

You will receive notifications by email! OSS-Fuzz is working on getting issues reported by way of Github and I expect that to be more stable soon!

> I have some other specific questions on OSS-Fuzz. I'll leave comments into your PR there.

Got it, I answered over there!

**Comment by rayluo** [comment]
> > By the way, are those existing emails in your current PR intended to be there?

> The existing emails are there just for us to help with the integration, for example, there may be something in the set up that breaks or similar when the fuzzers start running to continuously. Am happy to remove if you prefer but it's for us to assist in case of any mishappeninngs!

You do not have to remove them if those setup are useful to you. I was just not sure whether they were copy-and-paste errors. :-)
