### ISSUE TITLE
Support Azure AD B2C

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-python#52]
Support [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/)

**Comment by askpatrickw** [comment]
This is listed in the README as coming soon when it was first committed in December 2018. 
What's the timeline for adding B2C support?

**Comment by rayluo** [comment]
Patrick (@askpatrickw) you clearly did your homework digging out the history. :-)  Yes B2C has always been in [our roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki) since day 1. We have come [a long way since then](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases). Rest assured that we are [getting close](https://github.com/AzureAD/microsoft-authentication-library-for-python/milestones?direction=asc&sort=title&state=open) to pick it up. Thanks for your upvote which certainly helps [our planning (sorted by upvotes)](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues?q=is%3Aopen+label%3Aenhancement+sort%3Areactions-%2B1-desc). Please subscribe this issue to receive updates.
