### ISSUE TITLE
How to connect to Azure Database for MySQL -Single Server from Azure Functions(Python) using MSAL?

### ISSUE THREAD

**Issue by ecormaksin** [AzureAD/microsoft-authentication-library-for-python#523]
I refered [this sample code](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/5b135b2e82d0a8064b226b8ca3d2ff5959070b05/sample/confidential_client_secret_sample.py).

I want to let Azure Function to authenticate by Azure Active Directory.

I cannot understand how to connect to Azure Database for MySQL -Single Server  from Azure Functions using MSAL.
How do I configure `scope` and `endpoint` ?

**Comment by rayluo** [comment]
Similar suggestion as [the other question](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/522).

In particular, there is an older wiki page for [how to Connect to Azure SQL Database from ADAL Python](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Connect-to-Azure-SQL-Database). Now, ADAL Python is deprecated, but the concept and steps in that wiki page might still work for MSAL.
