### ISSUE TITLE
f89ce73d971effc9d64d06e5b4b1707c3e5c80fb

### ISSUE THREAD

**Issue by Santiagosaiz** [AzureAD/microsoft-authentication-library-for-python#525]
**Describe the bug**

**To Reproduce**
1. Go to our [off-the-shelf samples](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample) and pick one that is closest to your usage scenario. You should not need to modify the sample.
2. Follow the description of the sample, typically at the beginning of it, to prepare a `config.json` containing your test configurations
3. Run such sample, typically by `python sample.py config.json`
4. See the error
5. In this bug report, tell us the sample you choose, paste the content of the config.json with your test setup (which you can choose to skip your credentials, and/or mail it to our developer's email).

**Expected behavior**

**What you see instead**
Paste the sample output, or add screenshots to help explain your problem.

**The MSAL Python version you are using**
Paste the output of this
`python -c "import msal; print(msal.__version__)"`

**Additional context**

**Comment by rayluo** [comment]
The content above are all from our bug report template. What actual question do you want to ask?
