### ISSUE TITLE
Add support to use "TryAutoDetect" to enable auto detect

### ISSUE THREAD

**Issue by yingxumsft** [AzureAD/microsoft-authentication-library-for-python#526]
**Describe the bug**
Looks like we can only use True (boolean) to enable auto detect regional endpoint, rather than using "TryAutoDetect":
ATTEMPT_REGION_DISCOVERY = True  # "TryAutoDetect"

However, Azure.Identity library is using environment variable AZURE_REGIONAL_AUTHORITY_NAME ("TryAutoDetect"), which can not be set to true.
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py

Thus we cannot use auto detect with Azure.Identity library.

**To Reproduce**
Steps to reproduce the behavior - run following code in local machine, which trying to auto detect but it will fail as local machine is not AzureVM.

region = os.getenv("AZURE_REGIONAL_AUTHORITY_NAME")
if region is None or len(region) == 0:
    print("set region to auto detect")
    os.environ["AZURE_REGIONAL_AUTHORITY_NAME"] = "TryAutoDetect"

certificate_path = "your_local_cert.pfx"
certificate_credential = CertificateCredential(tenant_id='your tenant id',
                                            client_id='your client id',
                                            certificate_path=certificate_path,
                                            password="your password",
                                            send_certificate_chain=True)
token = certificate_credential.get_token('https://vault.azure.net/.default')
print(token)

**Expected behavior**
token should be acquired successfully.

**What you see instead**
CertificateCredential.get_token failed: Authentication failed: <urllib3.connection.HTTPSConnection object at 0x000001CAF0AE0D88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

**The MSAL Python version you are using**
1.20.0

**Additional context**

**Comment by rayluo** [comment]
> ```python
> os.environ["AZURE_REGIONAL_AUTHORITY_NAME"] = "TryAutoDetect"
> ...
> certificate_credential = CertificateCredential(...)
> ```

So, you were using the [Azure Identity library (which is part of the Azure SDK for Python)](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity). The Azure Identity is built on top of MSAL Python, but their calling patterns are different.

* Opt-in
  1. Azure Identity library may be using an environment variable `AZURE_REGIONAL_AUTHORITY_NAME=TryAutoDetect` to opt in (looping in @xiangyan99 to confirm)
  2. But here inside MSAL Python, the region behavior is controlled by an input parameter `ConfidentialClientApplication(..., azure_region=msal.ClientApplication.ATTEMPT_REGION_DISCOVERY)`.
  3. As long as Azure Identity maps its "TryAutoDetect" into MSAL Python's `msal.ClientApplication.ATTEMPT_REGION_DISCOVERY` (does it, @xiangyan99?), the downstream app developer does not have to know that MSAL's ATTEMPT_REGION_DISCOVERY is defined as a boolean `True`.
* No fallback.
  Unfortunately, once opted-in, the auto-detection behavior does not imply a graceful fallback. See more details in the "note" section in [MSAL Python's documentation](https://msal-python.readthedocs.io/en/latest/#msal.ConfidentialClientApplication.params.azure_region).

**Comment by xiangyan99** [comment]
Ray is right. You can use RegionalAuthority.AUTO_DISCOVER_REGION 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_enums.py#L15
in AZURE_REGIONAL_AUTHORITY_NAME to opt in.

**Comment by yingxumsft** [comment]
hi @xiangyan99 , thanks for the info. I tried to set that with following code:
    os.environ[EnvironmentVariables.AZURE_REGIONAL_AUTHORITY_NAME] = RegionalAuthority.AUTO_DISCOVER_REGION.value

On my local machine, the auto discover will return None region as expected, but the problem is MSAL think the configured region is 'True', thus it will use the 'True.r.login.microsoftonline.com' as the regional host in this code:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#:~:text=region_to_use%20%3D%20(,e.%20opted%20out

The reason I think is because Identiy library is passing 'True' as string to for azure_region in MSAL application, while MSAL application expect azure_region is boolean True to opt in auto discovery. For string 'True', MSAL application think it is any other configured region like 'westus2'.

![image](https://user-images.githubusercontent.com/86769410/210858225-faaa9166-42f9-4020-bf76-a045c53c0fb3.png)

**Comment by xiangyan99** [comment]
Looks like it is by design that ATTEMPT_REGION_DISCOVERY = True  # "TryAutoDetect"?

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L164

@rayluo ?

**Comment by rayluo** [comment]
> Looks like it is by design that [`ATTEMPT_REGION_DISCOVERY = True # "TryAutoDetect"`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.20.0/msal/application.py#L164)?

There is some history behind that line. MSALs accept either a string region name, or a special flag to represent auto-detect. MSAL .Net chose to use a [magic string](https://en.wikipedia.org/wiki/Magic_string) "TryAutoDetect" for the latter. MSAL Python tried that during prototyping, but eventually switched to a non-string value approach (so that all strings are considered a valid region name).

But if we are talking about the design, then, by design, none of implementation details above really matters in MSAL Python, because [MSAL Python only documents its auto-detect API](https://msal-python.readthedocs.io/en/latest/#msal.ConfidentialClientApplication.params.azure_region) as "use a special keyword `ClientApplication.ATTEMPT_REGION_DISCOVERY`", without even disclosing what value that constant actually is.

**Comment by rayluo** [comment]
Conclusion: The issue reported here is actually for MSAL's downstream library, the Azure Identity package, and the fix is provided there.

MSAL itself does not have to change the magic value, as long as the caller will stick with MSAL's documented constant's name [`ConfidentialClientApplication.ATTEMPT_REGION_DISCOVERY`](https://msal-python.readthedocs.io/en/latest/#msal.ConfidentialClientApplication.params.azure_region).
