### ISSUE TITLE
Does the msal ConfidentialClientApplication support ecdsa certs?

### ISSUE THREAD

**Issue by 3BK** [AzureAD/microsoft-authentication-library-for-python#534]
**Describe the bug**
Unable to acquire_jwt_token using ecdsa cert and ConfidentialClientApplication class.

**To Reproduce**
1. Upload an ECDSA pub cert to an "Azure Application"
2.  Instantiate your class
> app = msal.ConfidentialClientApplication(
>     client_id         = client_id
>     ,authority         = authority_url
>     ,client_credential = cred
>   )
3. request a JWT
> app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])

**Expected behavior**
Expected to receive a JWT

**What you see instead**
...
    jwt_token = acquire_jwt_token(keyfile, pubfile, passphrase, client_id, tenant_id)
  File "./HttpsAuthEmailClient.py", line 61, in acquire_jwt_token
    jwt_token = app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/application.py", line 2013, in acquire_token_for_client
    response = _clean_up(client.obtain_token_for_client(
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 752, in obtain_token_for_client
    return self._obtain_token("client_credentials", data=data, **kwargs)
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 771, in _obtain_token
    resp = super(Client, self)._obtain_token(
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 199, in _obtain_token
    self.client_assertion()  # Do lazy on-the-fly computation
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/assertion.py", line 61, in __call__
    self._buf = {VALUE: self._factory(), EXPIRES_AT: now + self._expires_in}
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/assertion.py", line 40, in <lambda>
    self.create_normal_assertion(a, i, s, expires_in=e, **kwargs),
  File ".../o365/venv38/lib64/python3.8/site-packages/msal/oauth2cli/assertion.py", line 114, in create_normal_assertion
    str_or_bytes = jwt.encode(  # PyJWT 1 returns bytes, PyJWT 2 returns str
  File ".../o365/venv38/lib64/python3.8/site-packages/jwt/api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File ".../o365/venv38/lib64/python3.8/site-packages/jwt/api_jws.py", line 114, in encode
    signature = alg_obj.sign(signing_input, key)
  File ".../o365/venv38/lib64/python3.8/site-packages/jwt/algorithms.py", line 378, in sign
    return key.sign(msg, padding.PKCS1v15(), self.hash_alg())
TypeError: sign() takes 3 positional arguments but 4 were given

**The MSAL Python version you are using**
1.21.0

**Additional context**

**Comment by rayluo** [comment]
> Unable to ... using ecdsa cert and ConfidentialClientApplication class.

[We believe](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2573#issuecomment-832334611) that the ECDSA cert is not supported by the Azure AD service side.

It doesn't harm if you want to change [MSAL Python's signing algorithm](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.21.0/msal/application.py#L669) from RS256 to something else, perhaps ES256 ([algorithm names came from here](https://pyjwt.readthedocs.io/en/stable/algorithms.html)), and see how that goes.

**Comment by krishnan206** [comment]
Tried changing MSAL Python's signing algorithm from RS256 to ES256, the traceback "TypeError: sign() takes 3 positional arguments but 4 were given" is gone, but still unable to acquire an access token.

**Comment by 3BK** [comment]
Not comfortable with ES256 anymore. Its probably "a bad idea'.

ED certs are safer. Should we add ed448+shake256 and ed25519+shake128 ?

Do you want me to cancel this issue and open a new issue????

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 3BK** [comment]
Hi Ray.

RSA seems like an CNSA 1.0 artifact.  (Now called CNSSP 15, Annex B.)
Is Microsoft on track for removing the obsolete RSA algorithm - as per CNSA 2.0 - or have things stalled.?
CNSA 2.0 timeline available upon request - offline.
                Hint: 2025 is coming very fast....

**Comment by 3BK** [comment]
CSA_CNSA_2.0_ALGORITHMS_.PDF (defense.gov)<https://media.defense.gov/2022/Sep/07/2003071834/-1/-1/0/CSA_CNSA_2.0_ALGORITHMS_.PDF>

From: Brent Kimberley
Sent: April 17, 2023 1:41 PM
To: AzureAD/microsoft-authentication-library-for-python ***@***.***>; AzureAD/microsoft-authentication-library-for-python ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [AzureAD/microsoft-authentication-library-for-python] Does the msal ConfidentialClientApplication support ecdsa certs? (Issue #534)

Hi Ray.

RSA seems like an CNSA 1.0 artifact.  (Now called CNSSP 15, Annex B.)
Is Microsoft on track for removing the obsolete RSA algorithm - as per CNSA 2.0 - or have things stalled.?
CNSA 2.0 timeline available upon request - offline.
                Hint: 2025 is coming very fast....

**Comment by bgavrilMS** [comment]
I confirm that the service does not support EC certs. I am not aware of support being added.

**Comment by 3BK** [comment]
Yah.  If you haven't done it now, you should probably aim for crystals-kyber

**Comment by 3BK** [comment]
https://www.microsoft.com/en-us/research/project/post-quantum-tls/

**Comment by 3BK** [comment]
Lots of time ;) 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/40867233/60ded2e5-85f9-4136-a25f-97563927b41b)
