### ISSUE TITLE
error signing in 

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-python#535]
Error Code: 80043490
Correlation Id: ac0cb5112d264898af4f4e76a17061a4
Timestamp: 2023-02-08T19:36:09.067Z

**Comment by rayluo** [comment]
That error code is not defined in [Azure AD error codes](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes#aadsts-error-codes). Can you share steps to reproduce this error, using one of our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/1.21.0/sample) that is closest to your app?
