### ISSUE TITLE
Screenshot (11 Feb 2023 7:02:52 pm)

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-python#536]
![Screenshot_20230211-190252.png](https://user-images.githubusercontent.com/114141548/218286253-1aaf1c66-bda1-4190-818c-112cdcc25b12.png)

**Comment by rayluo** [comment]
@jabelrod1121 , nice screenshot, but perhaps you pasted it into the wrong forum?
