### ISSUE TITLE
MSAL shows gibberish if `localhost` is accessed using HTTPS

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#546]
**Describe the bug**
MSAL shows gibberish ([mojibake](https://en.wikipedia.org/wiki/Mojibake)) if `localhost` is accessed using HTTPS.

**To Reproduce**
Run

```
az login --debug
```

The login URL is 
```
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?...redirect_uri=http%3A%2F%2Flocalhost%3A61886...
```

Even though `redirect_uri` is an HTTP URL `http://localhost:61886/`, we switch the protocol to HTTPS `https://localhost:61886/` and visit it in the browser. In the real world, the protocol may be changed by the browser's policy (https://github.com/Azure/azure-cli/issues/10426#issuecomment-528308713).

Then the browser will show `ERR_SSL_PROTOCOL_ERROR`:

![image](https://user-images.githubusercontent.com/4003950/227832671-bf5171ee-c743-4709-b99b-75048dadd94b.png)

In the terminal, MSAL shows gibberish characters because these are actually HTTPS-encrypted binary stream.

```
msal.oauth2cli.authcode: code 400, message Bad request version ('\x08\x9e\x87\x95]ÈeÏ9íÏ\x82\x8aUÇÑ~\x03\x91W\x00')
msal.oauth2cli.authcode: "▬♥☺☻☺☺ü♥♥_↨Ò1Ø¹6ÙÍß
«#p◄Á03ó#åy¦ð+Í }ºR;2þì7fâÅD¶apIè▼þµ*áÓ!V]-"ªª‼☺‼☻‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶/5☺☺ZZÿ☺☺-☻☺☺♥☻☻
                                                                                      i♣♥☻h2
↕►♦♦♦☺♣♣♣♠♠☺↨+♠**♥♦♥♥
☻☺►
☻hhttp/1.13+)☺↔ ZMÁ7ðó►ã_·]ÈeÏ9íÏUÇÑ~♥W" 400 -
msal.oauth2cli.authcode: code 400, message Bad request version ('\x02h2\x08http/1.1\x00')
msal.oauth2cli.authcode: "▬♥☺☻☺☺ü♥♥Ý¶5ã{ï£V♠ò_Ã♥
```

This issue is reported by https://github.com/Azure/azure-cli/issues/25935, and the solution is https://github.com/Azure/azure-cli/issues/10426#issuecomment-528308713.

**Expected behavior**
MSAL can consider capturing such error and warn the user incorrect protocol is used. I haven't deep dived into the implementation of [`http.server`](https://docs.python.org/3/library/http.server.html) yet, but it is totally possible that this can't be achieved by MSAL.

**Comment by jiasli** [comment]
My computer's locale setting:

![image](https://user-images.githubusercontent.com/4003950/227839269-af52ee0d-5797-4ebd-bdb2-747a6d13f9a8.png)

**Comment by rayluo** [comment]
Honestly not sure when we will get around to this. Marking it as an enhancement request, for now. :-)
