### ISSUE TITLE
Generate access token for a Managed identity

### ISSUE THREAD

**Issue by pievalentin** [AzureAD/microsoft-authentication-library-for-python#548]
**Bug description**

I am an Azure costumer. I can't use MSAL to generate an access token for the scope of my app reg using my managed identity.

I have this setup:
- I deployed an Azure function app that is validating access token of an Application registration. It checks that the Client has the correct role.
- I have a compute instance that is assigned a Managed identity. I want to send a HTTP request to my azure function with an access token generated for my Managed Identity.

It might be related to #58 

**To Reproduce**
1. Create an app reg with a custom role
2. Create a managed identity
3. Assign the custom role to the managed identity
4. Create a compute instance and assigned it the managed identity
5. In the compute instance run:
```python
from azure.identity import ManagedIdentityCredential
cred = ManagedIdentityCredential(client_id="<managed-identity-client-id>")
token = cred.get_token("api://<app-reg-client-id>/.default")
```
The code will run indefinitely

**Expected behavior**
After running `token = cred.get_token("api://<app-reg-client-id>/.default")` the token should be generated

**What you see instead**
![image](https://user-images.githubusercontent.com/14977219/230216319-4dae8af3-5472-4427-82ff-f55a425d83ba.png)
Code is still running and no token is generated.

**The MSAL Python version you are using**
1.21.0

**Comment by rayluo** [comment]
Hi @pievalentin , your code snippet is using a different library, [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python), so, you would want to create a similar github issue there.

This repo here is about Microsoft Authentication Library (MSAL) for Python. MSAL Python is currently implementing Managed Identity feature. If you are interested in trying out the bleeding edge, you can follow the instruction in #480 to try it out.

**Comment by pievalentin** [comment]
Oh my bad. Thanks a lot for the kind and fast help @rayluo. Will try what you suggested on my company laptop tomorrow morning!

**Comment by pievalentin** [comment]
My azureml environment is very restricted (SSL inspection), I have some trouble installing your draft PR. I am still working on it.
