### ISSUE TITLE
docs/how-to-enable-new-languages.md


### ISSUE THREAD

**Issue by Lyllt8** [AzureAD/microsoft-authentication-library-for-python#556]
https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/4774184022/jobs/8487737170#step:2:1

**Comment by rayluo** [comment]
Hey, @Lyllt8 , I understand that you are new to Github, so you might not know how to use Github features.
If you have issues to report, please report them on the right repo with proper description.

Meanwhile, I have to close your irrelevant issue here.
