### ISSUE TITLE
Error with code=flow["device_code"]

### ISSUE THREAD

**Issue by AncestorComposition** [AzureAD/microsoft-authentication-library-for-python#561]
**Describe the bug**
The sample application returns an error with code=flow["device_code" on line 1973 of application.py in acquire_token_by_device_flow

**To Reproduce**
1. Follow the directions at https://learn.microsoft.com/en-us/azure/active-directory/develop/web-app-quickstart?pivots=devlang-python&tabs=windows

**Expected behavior**
Application should run without errors 

**What you see instead**
The sample application returns an error with code=flow["device_code" on line 1973 of application.py in acquire_token_by_device_flow

**The MSAL Python version you are using**
Paste the output of this
1.22.0

**Comment by rayluo** [comment]
> To Reproduce
Steps to reproduce the behavior:
>    Follow the directions at https://learn.microsoft.com/en-us/azure/active-directory/develop/web-app-quickstart?pivots=devlang-python&tabs=windows

That link alone is not enough for us to reproduce your issue. In fact, we tested those steps before we published that doc.

Would you mind sharing your setting i.e. the `.env` file (except the CLIENT_SECRET)? Also, I believe you modified [the sample](https://github.com/Azure-Samples/ms-identity-python-webapp). What changes did you make?

**Comment by AncestorComposition** [comment]
Here is the full traceback:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/55901541/51c4e2c4-10f2-4781-ae4e-b7921c6be337)

**Comment by AncestorComposition** [comment]
I resolved the problem. The problem was due to the fact that the callback URI was http://localhost, creating a clash between @app.route(app_config.REDIRECT_PATH) and  @app.route("/")
