### ISSUE TITLE
need help in adding authentication using azure B2C in Kivy

### ISSUE THREAD

**Issue by venkataraja705** [AzureAD/microsoft-authentication-library-for-python#562]
This is not a Bug 
we are requesting for help!

I have developed a mobile application using kivy and kivymd
we are trying to add authentication in kivy using Azure AD B2C
we have found AZURE documentations on B2C authentication in python web application but could not find anything for kivy mobile application.

if we use userflows from mobile app. on sign in we will need to launch a browser window inside the mobile application itself.
but we do not want to do that.
please suggest any other alternatives or samples for making the user sign in from mobile login page itself.

reference: https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-android-app?tabs=kotlin
reference-python-web-app: https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-python-web-app?tabs=windows

**Comment by rayluo** [comment]
Microsoft provides [MSAL libraries](https://github.com/AzureAD) for Android and iOS. Please move your issue to the corresponding repos. Thanks.
