### ISSUE TITLE
Error AADSTS700025 when deploying Flask authentication APP to IIS.

### ISSUE THREAD

**Issue by AncestorComposition** [AzureAD/microsoft-authentication-library-for-python#571]
**Describe the bug**
Error AADSTS700025 when deploying Flask authentication APP to IIS.

**To Reproduce**
1. I followed the directions at https://learn.microsoft.com/en-us/azure/active-directory/develop/web-app-quickstart?pivots=devlang-python&tabs=windows and the authentication web app works when running on localhost.
2. I then tried to deploy the authentication Flask app to IIS, but the user gets error message "AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented." 

**Expected behavior**
User should be able to authenticate with the Flask app when the app is served via IIS.
**What you see instead**
"AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented." 

**The MSAL Python version you are using**
1.22.0

**Additional context**

**Comment by rayluo** [comment]
What is your app's redirect uri when it is deployed to IIS? And, is that redirect uri be configured as a web platform in Azure Portal?

**Comment by AncestorComposition** [comment]
The redirect uri when it is deployed to IIS is https://dapp000639/greet/getAToken.  I will have to check with our Azure Portal administrator to know the type of the URI.  What are the options?  What is the correct choice in this case?

**Comment by rayluo** [comment]
Per [taxonomy](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#configure-platform-settings), a Python-powered website is a Web application, not a SPA (single-page application).

You can try to change that redirect URI to Web (by delete and recreate?), or see if you can add a different URI whose type is Web, and see how that goes.

**Comment by rayluo** [comment]
As long as you do not use the same redirect URI for your app's different platforms (i.e. Web, Desktop, SPA, etc.), you shall be fine.
