### ISSUE TITLE
Specifying a custom redirect URI in the PublicClientApplication

### ISSUE THREAD

**Issue by ADNewsom09** [AzureAD/microsoft-authentication-library-for-python#574]
**Describe the bug**
Unable to specify a redirectURI in the form `http://localhost:1234/MyApp` when creating a `PublicClientApplication` or using that with `acquire_token_interactive`

**To Reproduce**
```
authUrl = 'https://login.microsoftonline.com/' + app_config.TENANT_ID
app = msal.PublicClientApplication(app_config.APP_ID, authority=authUrl)
token = app.acquire_token_interactive(scopes=app_config.SCOPES)
```

**Expected behavior**
Using other packages like the C# one, we have been able to access this API.

**What you see instead**
`AADSTS50011: The redirect URI 'http://localhost:49686' specified in the request does not match the redirect URIs configured for the application`

**The MSAL Python version you are using**
1.22.0

**Additional context**
We cannot change the redirect URI on the application because there is another application type that uses the bare localhost, and other connecting applications expect the http://localhost:1234/MyApp redirect URI. I see the [docs say](https://docs.python.org/3/library/functions.html#int)

> The port to be used to listen to an incoming auth response. By default we will use a system-allocated port. (The rest of the redirect_uri is hard coded as http://localhost.)
But that isn't the case with other packages.

**Comment by rayluo** [comment]
> **Additional context**
> We cannot change the redirect URI on the application because there is another application type that uses the bare localhost, and other connecting applications expect the http://localhost:1234/MyApp redirect URI.

What "other application type" uses the bare localhost?

Note that there are [different types (known as "platforms") of applications](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#configure-platform-settings). Typically, one app (identified by its unique client_id) can target multiple platforms, such as a "Web" platform using redirect URI `http://localhost:1234/path` for development and `https://example.com/path` for production, together with a "Mobile and desktop application" platform using bare `http://localhost`. They will all work together. You shouldn't need to specify a different redirect URI for `acquire_token_interactive()`.

**Comment by rayluo** [comment]
> there is an SPA platform target that uses bare `http://localhost:1234` ... in production

Out of curiosity, why is an in-production SPA app would use localhost as redirect URI? Shouldn't localhost be only for development purpose, and shouldn't the production redirect URI contain `https://YourCoolWebsite.com/...`?

**Comment by ADNewsom09** [comment]
There is of course interesting historical reasoning for this for us. I'm advocating for feature parity with the ms auth library for c#, which does support these paths.

**Comment by rayluo** [comment]
By any chance the website hosting your SPA app is publicly accessible so that I can take a quick look?
