### ISSUE TITLE
https://login.microsoftonline.com/ not a valid address? 

### ISSUE THREAD

**Issue by thomasteoh** [AzureAD/microsoft-authentication-library-for-python#582]
**Describe the bug**
Using python library version 1.23.0

msal.ConfidentialClientApplication appears to not recognise https://login.microsoftonline.com/ as a valid https url with a minimum of one segment in a path, even though this address is one that is suggested to be valid by the ValueError message

This was previously working without issue in 1.22.0

**To Reproduce**
Using a valid set of service principal details, msal.ConfidentialClientApplication is called with the address: https://login.microsoftonline.com/

msal.ConfidentialClientApplication(clientid, secret, "https://login.microsoftonline.com/")

**Expected behavior**
Expecting application to be accepted

**What you see instead**

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <command-3231369319067440>:1
----> 1 msal.ConfidentialClientApplication(
      2         clientid, secret, "https://login.microsoftonline.com/"
      3         )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/msal/application.py:544, in ClientApplication.__init__(self, client_id, client_credential, authority, validate_authority, token_cache, http_client, verify, proxies, timeout, client_claims, app_name, app_version, client_capabilities, azure_region, exclude_scopes, http_cache, instance_discovery, allow_broker)
    542 try:
    543     authority_to_use = authority or "https://{}/common/".format(WORLD_WIDE)
--> 544     self.authority = Authority(
    545         authority_to_use,
    546         self.http_client,
    547         validate_authority=validate_authority,
    548         instance_discovery=self._instance_discovery,
    549         )
    550 except ValueError:  # Those are explicit authority validation errors
    551     raise

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/msal/authority.py:76, in Authority.__init__(self, authority_url, http_client, validate_authority, instance_discovery)
     74 if isinstance(authority_url, AuthorityBuilder):
     75     authority_url = str(authority_url)
---> 76 authority, self.instance, tenant = canonicalize(authority_url)
     77 is_ciam = self.instance.endswith(_CIAM_DOMAIN_SUFFIX)
     78 self.is_adfs = tenant.lower() == 'adfs' and not is_ciam

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/msal/authority.py:163, in canonicalize(authority_or_auth_endpoint)
    161     if len(parts) >= 2 and parts[1]:
    162         return authority, authority.hostname, parts[1]
--> 163 raise ValueError(
    164     "Your given address (%s) should consist of "
    165     "an https url with a minimum of one segment in a path: e.g. "
    166     "https://login.microsoftonline.com/<tenant> "
    167     "or https://<tenant_name>.ciamlogin.com/<tenant> "
    168     "or https://<tenant_name>.b2clogin.com/<tenant_name>.onmicrosoft.com/policy"
    169     % authority_or_auth_endpoint)

ValueError: Your given address (https://login.microsoftonline.com/) should consist of an https url with a minimum of one segment in a path: e.g. https://login.microsoftonline.com/<tenant> or https://<tenant_name>.ciamlogin.com/<tenant> or https://<tenant_name>.b2clogin.com/<tenant_name>.onmicrosoft.com/policy
```

![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/7086928/bda2447e-1bea-4c3b-9dfb-cdb4d31b2320)

**The MSAL Python version you are using**
Paste the output of this
1.23.0

**Additional context**
Running in Azure Databricks

**Comment by rayluo** [comment]
> msal.ConfidentialClientApplication appears to not recognise https://login.microsoftonline.com/ as a valid https url with a minimum of one segment in a path, even though this address is one that is suggested to be valid by the ValueError message

The error message should contain `<path>` which was probably truncated when rendered on web. We will improve the error message in next release. Meanwhile, you can see the real error message by running this one-liner:

    python -c "from msal import ConfidentialClientApplication as CCA; print(CCA('id', client_credential='foo', authority='https://login.microsoftonline.com/'))"

> This was previously working without issue in 1.22.0

We are not able to reproduce this statement. Can you share your short test steps?

**Comment by thomasteoh** [comment]
@rayluo probably same issue as #583

**Comment by rayluo** [comment]
> @rayluo probably same issue as #583

No, it is different than #583. Did you change your calling code snippet recently? Please follow the test steps in my message above.
