### ISSUE TITLE
support: sovereign cloud 

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-library-for-python#59]
[This line](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/authority.py#L41) by hard coding to public azure blocks authentication in sovereign clouds. Please fix it soon

//CC @marstr @rayluo

**Comment by rayluo** [comment]
Admittedly, sovereign cloud scenario wasn't tested. In fact, it wasn't in the picture when we developed that line [3 years ago](https://github.com/AzureAD/microsoft-authentication-library-for-python/blame/dev/msal/authority.py#L41). We will take a look into this.

By the way, how does CLI works with sovereign cloud using ADAL Python today? I thought ADAL Python and MSAL Python behavior the same in this aspect.

**Comment by yugangw-msft** [comment]
No. ADAL works right now. You run "az cloud set -n AzureChinaCloud" and "az login" will work
