### ISSUE TITLE
Need Python OBO example linked from main article

### ISSUE THREAD

**Issue by willfiddes** [AzureAD/microsoft-authentication-library-for-python#591]
This article needs to be updated...
https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Acquiring-Tokens

The main article needs to link to correct Python obo docs > this might be because Python OBO docs dont exist?
All other flows link to pythin specific examples. Why not OBO?

**Comment by rayluo** [comment]
Indeed, MSAL Python does not yet have a standalone OBO sample. For now, you can refer to this [internal test case](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.24.0/tests/test_e2e.py#L602-L644) to see how OBO works.
