### ISSUE TITLE
How to integrate AAD with front-end and back-end applications?

### ISSUE THREAD

**Issue by lxf920125** [AzureAD/microsoft-authentication-library-for-python#595]
Dear,
I just find examples that the application gets authorized code and then acquire the access token, but my application contains front-end and back-end service, the front-end could get data from back-end service and they deployed on different servers, so how should I do this?

**Comment by rayluo** [comment]
Hi @lxf920125 , not sure what programming language(s) your apps will be built with, but if you are using Python, these are the [scenarios supported by MSAL Python library](https://msal-python.readthedocs.io/en/latest/). In particular, one of them is a [web app sample](https://learn.microsoft.com/azure/active-directory/develop/quickstart-web-app-python-sign-in?tabs=windows) which users sign in to that web app and access pages there.

If you were talking about a SPA + WebApi approach, the SPA is typically implemented in Javascript so you shall look into [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js), your web api can be implemented in any language. We do not currently provide a web api sample in Python to demonstrate token validation, but you can get some idea from this [Token Validation documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-tokens).
