### ISSUE TITLE
Reported vulnerability: Improper Neutralization of Special Elements in Data Query Logic

### ISSUE THREAD

**Issue by kevindixon** [AzureAD/microsoft-authentication-library-for-python#597]
**Describe the bug**
See https://security.snyk.io/vuln/SNYK-PYTHON-MSAL-5904284
Reported as affecting all `msal` versions

**To Reproduce**
N/A

**Expected behavior**
No vulnerability reported

**What you see instead**
See https://security.snyk.io/vuln/SNYK-PYTHON-MSAL-5904284

**The MSAL Python version you are using**
`1.24.0`

**Additional context**
None

**Comment by kevindixon** [comment]
@rayluo this is still reported by Snyk as a vulnerability in `1.24.1` - is there some process to get Snyk to re-assess?

**Comment by kevindixon** [comment]
@rayluo Re-tried this morning, and Snyk no longer reports `1.24.1` as vulnerable - thanks for the fix!

**Comment by bgavrilMS** [comment]
Just to update the thread - the vulnerability reported was discussed by Microsoft Security team and deemed to be of a lower severity / impact, and not requiring a CVE. 

CVEs remain the official mechanism for alerting app developers of vulnerabilities in their dependencies.
