### ISSUE TITLE
Issuer URL is sts.windows.net instead of login.microsoftonline.com

### ISSUE THREAD

**Issue by hpsjakob** [AzureAD/microsoft-authentication-library-for-python#600]
Hi,

I'm trying to implement a OAuth using this lib. 
My problem is that the issuer of the token is "https://sts.windows.net" instead of "https://login.microsoftonline.com/.../v2".

According to [this thread](https://stackoverflow.com/questions/59790209/issuer-in-access-token-from-azure-active-directory-is-https-sts-windows-net-wh) this is caused by a wrong token version. So I've tried setting ` "accessTokenAcceptedVersion": 2` and waited a few days. However, it did not change.

I'm using the lib in version 1.24.0. It would be great if someone could give me a hint!

**Comment by bgavrilMS** [comment]
Hi @hpsjakob - can you please clarify what you mean by "implement a OAuth"? 

What type of application do you have? A console / desktop app, a web site or a web api? And what are you trying to do  - do you need to sign-in users or do you need to call a protected downstream web api (e.g. Microsoft Graph, or your own API)?

`https://sts.windows.net/` is equivalent to `https://login.microsoftonline.com/` and a token validator needs to take that into account.

**Comment by hpsjakob** [comment]
Hi,
thnak you for the quick reply.
I'm building a console Application.
In a nutshell my App looks like this:

```python
app = PublicClientApplication( "XXX",  authority="https://login.microsoftonline.com/XXX")
response = app.acquire_token_interactive(["user.read"])
return response['access_token']
```

Then I use the token agains an custom Spring Boot app that verifies the token usign [this mechanism](https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/jwt.html).

There we validate that the JWT issuer matches `https://login.microsoftonline.com/XXX/v2.0`.

We're doning the same from a Single Page App (JS) and from there we get the JWT with https://login.microsoftonline.com issuer.

Do you habe a hint / example for a correct Token valudation in Spring Boot?

**Comment by bgavrilMS** [comment]
Unfortunately we do not yet have an AAD token validator for Java, only for .NET and for NodeJS.

Is there a way to pass in a list of allowed issuers in the Spring Boot token validation package? AAD maintains a list of names for each cloud that are valid issuers. See https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize

**Comment by bgavrilMS** [comment]
The format of the token (v1 or v2) depends on the resource it is for https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#token-formats. Since you added `"accessTokenAcceptedVersion": 2`, you'll be getting v2 access tokens consistently.

The hostname of the issuer is one of the 4 possible values, as per discovery call above. The .NET token validator makes the discovery call on its own and hides this complexity.

**Comment by hpsjakob** [comment]
hm ok.
So I'll add a handling for the different URLs.
However now I took a closer look on the Token and it contains the claim `"ver": "1.0",` so I guess there is still somethign else wrong with the version.

I double checked, I my Manifest it sais `"accessTokenAcceptedVersion": 2,`.

Is there something else I need to look out for?

**Comment by bgavrilMS** [comment]
Hmm, something is wrong then. Do you have a different app registration for the client (the python console app) and the web api (the Java Spring) ? The setting should go on the web api app registration.

**Comment by hpsjakob** [comment]
yes, it's the same App Registration. But two different Platform configurations. But this should not be a problem, right?
The `accessTokenAcceptedVersion` I added right in top of the Manifest file.

**Comment by bgavrilMS** [comment]
I don't think it should be a problem, but you can try creating a separate app and expose a web api on it and change `accessTokenAcceptedVersion=2` and check. 

In any case, the issuer alias problem is the same.

**Comment by hpsjakob** [comment]
Hi,
I compared my code again to the one in our SinglePage app and found that I was midding the scope `api://XXX/access_as_user`. Once I specified this scope I recieved a token with V2.
Strage...

Anyway I think we can close this.
