### ISSUE TITLE
GA the broker experience, including POP, with per-OS opt-in to broker

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-python#607]

**Comment by rayluo** [comment]
Are you talking about broker-on-Windows (WAM)?

**Comment by bgavrilMS** [comment]
Yes.

**Comment by bgavrilMS** [comment]
> Are you talking about broker-on-Windows (WAM)?

Yes

**Comment by rayluo** [comment]
"Per-OS opt-in to broker" was shipped in [MSAL Python 1.25](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.25.0), and POP was shipped in [1.26](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.26.0).
