### ISSUE TITLE
PublicClientApplication w/ Username and Password Flow Reveals Error-Code 7000218

### ISSUE THREAD

**Issue by chadhpaine** [AzureAD/microsoft-authentication-library-for-python#611]
**Describe the bug**
I have been attempting to use [username_password_sample.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/username_password_sample.py) to construct an application allowing an authorized user to run a script against the MS Graph API.

config.json:
```
{
    "authority": "https://login.microsoftonline.com/organizations",
    "client_id": "<my-azure-application-id>",
    "username": "<my-email>@<my-organization>.com",
    "password": "<my-password>",
    "scope": ["User.Read"],
    "endpoint": "https://graph.microsoft.com/v1.0/me"
}
```

**To Reproduce**
1. Go to our [off-the-shelf samples](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample) and pick one that is closest to your usage scenario. You should not need to modify the sample.
2. Follow the description of the sample, typically at the beginning of it, to prepare a `config.json` containing your test configurations
3. Run such sample, typically by `python sample.py config.json`
4. See the error
5. In this bug report, tell us the sample you choose, paste the content of the config.json with your test setup (which you can choose to skip your credentials, and/or mail it to our developer's email).

**Expected behavior**
A token can be retrieved, if the user is authorized.

**What you see instead**
```
Token acquisition failed
{'error': 'invalid_client', 'error_description': "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: b041fb2d-9d65-4e12-833a-d95065208300\r\nCorrelation ID: 6965ec8e-fe4b-416f-b918-7960caf26cab\r\nTimestamp: 2023-10-26 18:45:25Z", 'error_codes': [7000218], 'timestamp': '2023-10-26 18:45:25Z', 'trace_id': 'b041fb2d-9d65-4e12-833a-d95065208300', 'correlation_id': '6965ec8e-fe4b-416f-b918-7960caf26cab', 'error_uri': 'https://login.microsoftonline.com/error?code=7000218', 'claims': '{"access_token":{"capolids":{"essential":true,"values":["95216c5c-d0c0-41c0-b3d1-737556c043db"]}}}'}
Press Ctrl-C to stop.
```

**The MSAL Python version you are using**
1.24.1
**Additional context**
Using a home-grown script, I am able to retrieve a token using the ConfidentialClientApplication flows ([for automated access to the APIs](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_certificate_sample.py)) but not when using the PublicClientApplication, same error-conditions.

**Comment by chadhpaine** [comment]
Also reproduced using the [interactive_sample.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/interactive_sample.py), same error-conditions (had to add `print(result)` at line 89 to see the error json).

**Comment by rayluo** [comment]
> Token acquisition failed
{'error': 'invalid_client', 'error_description': "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: b041fb2d-9d65-4e12-833a-d95065208300\r\n..., 'error_uri': 'https://login.microsoftonline.com/error?code=7000218', 'claims': '{"access_token":{"capolids":{"essential":true,"values":["95216c5c-d0c0-41c0-b3d1-737556c043db"]}}}'}

> Also reproduced using the [interactive_sample.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/interactive_sample.py), same error-conditions

I believe when your app was registered with client credentials in the Azure Portal, it is expected to always be used with its credential (i.e., programming with MSAL's `ConfidentialClientApplication`). You can try to change the `username_password_sample.py` sample and run it one more time. Keep in mind though, the [username password flow has its own quirks](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication) so that you may run into other errors.

**Comment by chadhpaine** [comment]
> I believe when your app was registered with client credentials in the Azure Portal, it is expected to always be used with its
> credential (i.e., programming with MSAL's ConfidentialClientApplication). 

Thanks @rayluo - this was something I was unaware of. It's unfortunate if that's the case, but at that point the issue lies not with this library so much as with my understanding of which ways the library could be used under different scenarios.

**Comment by rayluo** [comment]
It is actually an expected behavior, [defined in the specs](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2.1):

    Confidential clients or other clients issued client credentials MUST
    authenticate with the authorization server

**Comment by chadhpaine** [comment]
After considering the spec and reevaluating the app-configuration, I did manage to get user-based authentication working. But as you mentioned, an application configured for use by public authentication flows cannot also be configured as a confidential-client application, and vise-versa. Two separate application profiles would be required - one for user-facing invocations and another for unattended operations.

Thanks again for pointing me in the right direction.

**Comment by chadhpaine** [comment]
> If you go with a different route, by registering [different redirect_uri](https://learn.microsoft.com/en-us/entra/identity-platform/msal-client-application-configuration#redirect-uri) for your same app, it shall be able to behave as a public client or a confidential client, based on which redirect uri was in use. I have seen same app using interactive_sample.py and Web App sample, when being deployed on different environments.

Just thought it worth following-up - it's thanks to this comment that I was able to enable dual-authentication (public / confidential) in the same application - my original configuration tried to used the same custom-address for both the web and desktop platforms, thus the conflict. That said - I found that the interactive flow is anyway needed for new users to 'consent' to the application's use, so it too will be involved in the final product. All in all, issue resolved 🥇 Thank you Ray.
