### ISSUE TITLE
Sello C#

### ISSUE THREAD

**Issue by Lyllt8** [AzureAD/microsoft-authentication-library-for-python#631]
https://github.com/Jesusdebug/Razor.BlogWeb/tree/master

**Comment by rayluo** [comment]
Duplicate of #619

**Comment by justinclift** [comment]
Note that this user appears to be a bot, creating issues with random text in repos. :frowning:

(found by them submitting multiple issues like this to the sqlitebrowser repos)

I've just reported this account to GitHub ("spammer").  Hopefully they'll nuke it.
