### ISSUE TITLE
[Feature Request] AAD client assertions should be computed using SHA 256 and an approved padding scheme

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-python#639]
### MSAL client type

Confidential

### Problem Statement

When MSAL creates the client assertion, it uses PKCS1 padding for digital signature and SHA1 as x5t claim. These are old crypto algorithms and we need to move to newer versions. The STS is building support.

See ESTS work items :

https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2655345
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2704466

### Proposed solution

Use x5t#s256 and PSS padding when talking to ESTS, CIAM, B2C(?) but not with ADFS.

 ### Original issue

 https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4428

**Comment by rayluo** [comment]
When will MSALs need to support this? It seems the [eSTS support is currently still in test slice](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4464/files#diff-da75e532ce600bea8a227e5b9c121d1d844336644d86f6acd90295addbb8f4e1R256)?

**Comment by bgavrilMS** [comment]
Should be in prod by end of Jan. I'm still following up with ADFS, B2C etc.
