### ISSUE TITLE
Feature Request: Removing app tokens

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-python#640]
Problem description: Historically, [there is no api in MSAL to remove tokens obtained from `AcquireTokenForClient()`](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/clear-token-cache#web-api-and-daemon-apps). Therefore, there is no way for an app to "log out" a service principal.

Proposal: MSALs add a new API ~`ConfidentialClientApplication.RemoveAppTokens()`~ `ConfidentialClientApplication.remove_tokens_for_client()`.

* It will purge app tokens that match the current app's authority (host + tenant) and client_id.
* It does not accept a `scope` parameter, because our intention is to purge all app tokens for the current app, regardless of their scopes.
* It will NOT purge user tokens obtained by this app.

**Comment by bgavrilMS** [comment]
CC @jmprieur @localden @pmaytak @gladjohn @trwalke - let's discuss about this next time we meet.

**Comment by localden** [comment]
@rayluo @bgavrilMS if the _app_ tokens are purged and the _user_ tokens are not, does it have any implications on the end-user experience?

We probably should spec this out.

**Comment by rayluo** [comment]
> @rayluo @bgavrilMS if the _app_ tokens are purged and the _user_ tokens are not, does it have any implications on the end-user experience?
> 
> We probably should spec this out.

I believe _app_ tokens and _user_tokens are independent with each other. This was also called out in the 3rd bullet point in this issue's description.

BTW, there was another github issue came in yesterday, which was actually the same topic. I was proposing a [different function name `remove_tokens_for_client()` there](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/649#issuecomment-1896262384).

**Comment by bgavrilMS** [comment]
@localden - to remove user tokens, the pattern is 

```csharp
var app = PublicClient or ConfidentialClient;
var accounts = await app.GetAccounts(); 

foreach (var acc in accounts)
    app.Remove(acc);
```

So the API is very much focused on the concept of "Account" which is a materialization of a user in a tenant. If you fetch app tokens, `GetAccounts` returns null.

To me it makes sense to not try to use the user token removal pattern for service principals, but would like to know your opinion.

**Comment by localden** [comment]
> @localden - to remove user tokens, the pattern is
> 
> ```cs
> var app = PublicClient or ConfidentialClient;
> var accounts = await app.GetAccounts(); 
> 
> foreach (var acc in accounts)
>     app.Remove(acc);
> ```
> 
> So the API is very much focused on the concept of "Account" which is a materialization of a user in a tenant. If you fetch app tokens, `GetAccounts` returns null.
> 
> To me it makes sense to not try to use the user token removal pattern for service principals, but would like to know your opinion.

Makes sense to keep the _user_ and _app_ token patterns somewhat separate. If we treat "Account" as materialization of users and tenants, what is the same alternative for apps?

**Comment by rayluo** [comment]
> > @localden - to remove user tokens, the pattern is
> > ```cs
> > var app = PublicClient or ConfidentialClient;
> > var accounts = await app.GetAccounts(); 
> > 
> > foreach (var acc in accounts)
> >     app.Remove(acc);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So the API is very much focused on the concept of "Account" which is a materialization of a user in a tenant. If you fetch app tokens, `GetAccounts` returns null.
> > To me it makes sense to not try to use the user token removal pattern for service principals, but would like to know your opinion.
> 
> Makes sense to keep the _user_ and _app_ token patterns somewhat separate. If we treat "Account" as materialization of users and tenants, what is the same alternative for apps?

I think that "alternative" has long been implicitly established by its acquisition method's naming, `AcquireTokenForClient()`. So, they are "tokens for client", as opposite to "tokens for a user/account". That's also why I would suggest NOT bother inventing a new concept/noun, we can just have a new API following the same naming pattern as "RemoveToken<b>s</b>ForClient()`.
