### ISSUE TITLE
Power BI token issue

### ISSUE THREAD

**Issue by Royy10** [AzureAD/microsoft-authentication-library-for-python#647]
I am trying to connect Power BI with my application using the MSAL library to generate access tokens for authenticating to the Power BI workspace for the dataset I am using for my application. The application uses using langchain Power BI agent to generate DAX queries using LLM. Now, it is working for the first couple of hours but after a certain time, it is throwing the following error:

) Error: TokenError: Could not login to PowerBI, please check your credentials.. Please supply a new DAX query.

**Comment by rayluo** [comment]
Tokens have their lifetime, which can be known from their `expires_in` attribute in each successful token response. You can check yours to confirm or rule out whether your issue was caused by token expiration.

After token expired, you can call MSAL's acquire_token_silent() to get a new token. Please refer to [the API doc](https://msal-python.readthedocs.io/) and/or the samples in this repo.

**Comment by Royy10** [comment]
@rayluo Thanks for the response. But I am already using this logic where I am regenerating the token after 1 hour and passing it and still getting the error. When I am checking the API, it is throwing error 429 saying we have maxed out the 120 API call limit for Power BI rest api. Can you suggest how this can be tackled so the application can still answer questions and we overcome this tokenError that is being showed.

**Comment by rayluo** [comment]
> When I am checking the API, it is throwing error 429 saying we have maxed out the 120 API call limit for Power BI rest api. Can you suggest how this can be tackled so the application can still answer questions and we overcome this tokenError that is being showed.

I'm afraid that it is no longer a token acquisition issue. It is how or whether you can bypass PowerBI's threshold control. Please ask your question in some PowerBI forum.
