### ISSUE TITLE
 "client_id": "your_client_id" < Microsoft can explain that better 

### ISSUE THREAD

**Issue by sijucm** [AzureAD/microsoft-authentication-library-for-python#659]
For example, I came from Microsoft pages on desktop clients and there also I see these clientIds and then I came here. All documentation says client-id: : " your client id". Microsoft, please give some useful documentation or please do not add junk to waste time. What client Id for a desktop application? Do I have to register an application even for a desktop client using username and password??? I wanted to automate something for my own account and it is another 2 hours wasted trying to find some info out of what Microsoft creates

**Comment by rayluo** [comment]
Hi, @sijucm , thanks for your constructive criticism.

> For example, I came from Microsoft pages on desktop clients and there also I see these clientIds and then I came here. All documentation says client-id: : " your client id".

You did not provide links to the docs that you referred to. But presumably, when it comes to [a short code snippet](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.26.0/sample/interactive_sample.py#L9) or any quote derived from it, only a short placeholder such as `your client id` is currently used. We can probably improve it by [adding a doc link](https://github.com/AzureAD/microsoft-authentication-library-for-python/compare/document-client-id?expand=1).

> What client Id for a desktop application? **Do I have to register an application even for a desktop client using username and password???** I wanted to automate something for my own account and it is another 2 hours wasted trying to find some info out of what Microsoft creates

The short answer to the highlighted question is "yes, always". The authentication/authorization model is always about the relationship and interaction among these [4 roles](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols#roles-in-oauth-20), and client is one of them.

Generally speaking, each input parameters of a library implies that its existence cannot be abstracted away from this library, it is therefore a concept that the caller shall understand beforehand. While we can and will add some links here and there into our samples, your investment on reading some overall docs will quickly pay themselves.
