### ISSUE TITLE
[Feature Request] Need support for ML managed identity

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-python#674]
### MSAL client type

Confidential

### Problem Statement

Today we support ml managed identity in azure-identity library. Please add the support in MSAL too.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/azure_ml.py

**Comment by xiangyan99** [comment]
I think so. AML MSI support is already GAed in identity library (for a long time :)).

It is a blocker from moving identity MSI implementation to msal.

**Comment by rayluo** [comment]
> > Hmm, is this something new we need to support for GA of MSI in MSALs?
>
> I think so. AML MSI support is already GAed in identity library (for a long time :)).
> 
> It is a blocker from moving identity MSI implementation to msal.

To clarify, @bgavrilMS 's question was more about "how about other non-Python MSALs".

@xiangyan99 , did you mention that the Managed Identity for Machining Learning is currently in Azure Identity for Python only?

**Comment by xiangyan99** [comment]
> > > Hmm, is this something new we need to support for GA of MSI in MSALs?
> > 
> > 
> > I think so. AML MSI support is already GAed in identity library (for a long time :)).
> > It is a blocker from moving identity MSI implementation to msal.
> 
> To clarify, @bgavrilMS 's question was more about "how about other non-Python MSALs".
> 
> @xiangyan99 , did you mention that the Managed Identity for Machining Learning is currently in Azure Identity for Python only?

Yes. Today only Python has it.
