### ISSUE TITLE
[Feature Request] Support PFX certificate authentication

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#684]
### MSAL client type

Confidential

### Problem Statement

MSAL currently requires PEM certificate for `ConfidentialClientApplication`:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/52b1fc5a442ff5dd33f48ce717f1032c8002ea9e/msal/application.py#L226-L228

The conversion logic is deferred to downstream application, such as Azure Identity library.

### Proposed solution

MSAL itself can support PFX certificate authentication so that other clients such as Azure CLI can also benefit from it.

See https://github.com/Azure/azure-cli/issues/28699

**Comment by rayluo** [comment]
See also the first comment in #685

**Comment by rayluo** [comment]
Documented in the last paragraph of [this parameter](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.client_credential).
