### ISSUE TITLE
[Bug] Eliminate sample dependency on https://pypi.org/project/identity/

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-python#691]
Details to be decided...

**Comment by rayluo** [comment]
The following 4-in-1 samples have switched to use a dependency hosted in Microsoft-owned repo.
* https://github.com/Azure-Samples/ms-identity-python-webapp
* https://github.com/Azure-Samples/ms-identity-python-webapp-django

Future samples will also follow same approach. This issue can be closed now.
