### ISSUE TITLE
Create a QuickStart sample

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-python#70]
Create a quick start, concept to be found here:

Javascript qs, notice how we are using tags for what goes to the portal and docs.
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-javascript

The md file from docs and convert it into HTML based on the tags for it to surface in portal.
Detailed instructions shared internally.

UPDATED: Some relevant docs that might also benefit from this QuickStart sample. The following content is quoted from an [internal work item](https://dev.azure.com/azuretracking/Azure%20tracking/_workitems/edit/424).

The following docs should contain code snippets for Python and other language: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration

**Comment by jmprieur** [comment]
@abhidnya13 : there were improvements to the structure of the quickstarts since the JavaScript one. Let's rather get inspiration from the Java one which is the most recent.

**Comment by abhidnya13** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/87359

**Comment by jmprieur** [comment]
The quickstart is available from https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-python-webapp

Thanks @abhidnya13 !
