### ISSUE TITLE
[Feature Request] Re-enable username password flow in Windows broker code path

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-python#702]
### MSAL client type

Public

### Problem Statement

In a recent meeting on May 6th, we agreed that the username password flow (a.k.a. ROPC), albeit inadvisable, is not ready to be deprecated. So, we shall re-enable its implementation in this code base.

**Comment by jiasli** [comment]
We are aiming to enforce MFA for all Azure CLI users on all tenants. Username password flow will not be possible in that case.

Also see https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/microsoft-will-require-mfa-for-all-azure-users/ba-p/4140391

**Comment by fengga** [comment]
PBI created at: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2944387

**Comment by fengga** [comment]
PR https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/712 merged.
We can consider closing this issue.

**Comment by rayluo** [comment]
Implemented in #712 and #714. Will be shipped in the next release.
