### ISSUE TITLE
[Bug] WAM login fails: User cancelled the Accounts Control Operation

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-library-for-python#707]
**Describe the bug**
See https://github.com/Azure/azure-cli/issues/28997

Customer verbatim:

- The window pops up and the error is simultaneous almost.
- Got same issue on Windows 11 with Windows PowerShell as administrator.
- It actually hangs Windows Terminal.
- If I dismiss the Sign in dialog, the console could not be focused anymore that I need to kill it by task manager.

**Comment by iulico-1** [comment]
Resolving the issue as it's been fixed already.

**Comment by rayluo** [comment]
Indeed, fixed in [MSAL Python 1.28.1](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.28.1)
