### ISSUE TITLE
[Feature Request] Support federated credentials + managed identity support for Azure Web App

### ISSUE THREAD

**Issue by ericyu-microsoft** [AzureAD/microsoft-authentication-library-for-python#735]
### MSAL client type

Confidential

### Problem Statement

Enable support federated credentials + managed identity from Azure Web App

So we can remove password from App registration and switch to managed identity

<img width="945" alt="image" src="https://github.com/user-attachments/assets/33ca2c9d-b1b4-4c4a-bc23-f6ef5d3f6c1b">

**Comment by bgavrilMS** [comment]
This is supported by the SDKs, so we can't do anything from here. https://learn.microsoft.com/en-us/azure/devops/pipelines/release/configure-workload-identity?view=azure-devops&viewFallbackFrom=azure-devops.

MSI + FIC is currently restricted to 1p apps. See the doc above for more details.
