### ISSUE TITLE
[Feature Request] Option to launch interactive auth on a different browser

### ISSUE THREAD

**Issue by choonchernlim** [AzureAD/microsoft-authentication-library-for-python#749]
### MSAL client type

Public

### Problem Statement

I currently use the delegated auth flow approach by using `app.acquire_token_interactive(..)`, which launches my default browser (Brave browser, in this case) on MacOS. 

However, due to my institution's configuration, the authentication flow gets stuck indefinitely on the "Set up your device to get access" page. If I change my default browser to Chrome, it works successfully.

I noticed [setting the preferred browser using the environment variable](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L135) is possible. However, it is only applicable to Linux.

### Proposed solution

Is it possible to specify a different browser programmatically without changing the default browser on my Mac? 

One way is to [remove the Linux platform check](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L128-L129) to allow other platforms to specify different browser via environment variable, too.

Thank you.

**Comment by rayluo** [comment]
I haven't tried it on Mac, but the Python documentation hints that [Python will honor the `BROWSER` env var](https://docs.python.org/3/library/webbrowser.html) ... also on Mac? Alternatively, you may go down the rabbit hole like [this](https://medium.com/@achhunna/set-macos-default-browser-using-cli-1f64102d9ed6). Will that work for you?

**Comment by choonchernlim** [comment]
With my default browser set to Brave on my Mac, this is what I tried:

```python
os.environ['BROWSER'] = 'chrome' # Opens Brave
os.environ['BROWSER'] = 'google-chrome' # Opens Brave
os.environ['BROWSER'] = 'chromium' # Opens Brave
os.environ['BROWSER'] = 'chromium-browser' # Opens Brave
os.environ['BROWSER'] = 'firefox' # Opens Firefox, but my institution doesn't support this browser
```

Somehow, webbrowser has difficulty differentiating a chromium browser like Brave from Chrome (vice versa).

Regarding that rabbit hole, I'm a little hesitated because I believe it will change the default browser permanently, unless I rerun it to change it back.

**Comment by rayluo** [comment]
> I haven't tried it on Mac, but the Python documentation hints that [Python will honor the `BROWSER` env var](https://docs.python.org/3/library/webbrowser.html) ... also on Mac?

Quoted from the doc, "If the environment variable BROWSER exists, it is interpreted as the [os.pathsep](https://docs.python.org/3/library/os.html#os.pathsep)-separated list of browsers to try ahead of the platform defaults. When the value of a list part contains the string `%s`, then it is interpreted as a literal browser command line to be used with the argument URL substituted for `%s`; ..."

Can you try BROWSER="/path/to/your/chrome/executable %s"?

**Comment by choonchernlim** [comment]
I think I got it! The path is a little convoluted, but I was able to launch it with Chrome now!

```python
# default browser on Mac = Brave

os.environ['BROWSER'] = "/Applications/Google\ Chrome.app %s"  # Opens Brave
os.environ['BROWSER'] = '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome %s'  # Opens Chrome

app = msal.PublicClientApplication(CLIENT_ID, authority=AUTHORITY)
```

Thank you very much for your help, @rayluo! I will close this ticket.
