### ISSUE TITLE
[Bug] Brokered auth on macOS fails when `prompt="none"`

### ISSUE THREAD

**Issue by pvaneck** [AzureAD/microsoft-authentication-library-for-python#757]
**Describe the bug**

When performing brokered authentication on macOS, the app crashes with `AttributeError: 'NoneType' object has no attribute 'pop'` when `prompt="none"` is passed to `acquire_token_interactive`.

**To Reproduce**

```python
   import msal

   tenant_id = "72f988bf-86f1-41af-91ab-2d7cd011db47"  # Microsoft tenant ID
   client_id = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"  # Azure CLI App ID

   app = msal.PublicClientApplication(
       client_id=client_id,
       authority=f"https://login.microsoftonline.com/{tenant_id}",
       enable_broker_on_windows=True,
       enable_broker_on_mac=True,
   )
   result = app.acquire_token_interactive(
       scopes=["https://graph.microsoft.com/.default"],
       prompt=msal.Prompt.NONE,
       parent_window_handle=app.CONSOLE_WINDOW_HANDLE,
   )
   print(result)
```

**Expected behavior**

The app should not crash. Instead, it should at least have the same behavior as `prompt="select_account"` if a default account is not supported on macOS. Related: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/672

**What you see instead**

```sh
Traceback (most recent call last):
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/paul/mac-broker-test.py", line 38, in <module>
    test_msal()
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/paul/mac-broker-test.py", line 28, in test_msal
    result = app.acquire_token_interactive(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/.venv/lib/python3.12/site-packages/msal/application.py", line 2121, in acquire_token_interactive
    response = self._acquire_token_interactive_via_broker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/.venv/lib/python3.12/site-packages/msal/application.py", line 2202, in _acquire_token_interactive_via_broker
    response = _signin_silently(  # Unlike OIDC, it doesn't honor login_hint
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/.venv/lib/python3.12/site-packages/msal/broker.py", line 155, in _signin_silently
    return _convert_result(
           ^^^^^^^^^^^^^^^^
  File "/Users/paulvaneck/dev/paulvaneck/azure-sdk-for-python/sdk/identity/azure-identity-broker/.venv/lib/python3.12/site-packages/msal/broker.py", line 92, in _convert_result
    telemetry.pop("wam_telemetry", None)  # In pymsalruntime 0.13, it contains PII "account_id"
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pop'

```

**The MSAL Python version you are using**

msal==1.31.0
pymsalruntime==0.17.0

**Additional context**

Company Portal is installed and `prompt="select_account"` works fine.

**Comment by rayluo** [comment]
> **Expected behavior**
> 
> The app should not crash. Instead, it should at least have the same behavior as `prompt="select_account"` if a default account is not supported on macOS. Related: #672

There are two things here.

1. That "AttributeError: 'NoneType' object has no attribute 'pop'" exception was a bug in `msal[broker]`'s dependency. That exception is expected to be gone when that package ships a new version.
2. The `prompt="none"` is never meant to automatically fall back to `prompt="select_account"`. Quoted from [its specs](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest),

   > none
   >
   > The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request.

   So, MSAL Python's erroring out (for a valid reason) is one of the valid outcomes here. If you want the fallback behavior, you should keep the `prompt` parameter absent rather than specifying a `prompt="none"`.

I would suggest close this issue here. And keep the other feature request #672 open for whether the mac broker shall support `acquire_token_interactive(..., prompt="none")`. When/if the PyMsalRuntime package supports that, MSAL Python will automatically pick up that behavior.

**Comment by pvaneck** [comment]
Sure, thanks @rayluo. I will try out the new release of `pymsalruntime` when that is available, and will control the fallback behavior from the identity sdk side as you described.
