### ISSUE TITLE
_get_arc_endpoint references wrong path for azcmagent/bin

### ISSUE THREAD

**Issue by msalwen** [AzureAD/microsoft-authentication-library-for-python#762]
The line linked below checks for the existence of `/var/opt/azcmagent/bin/himds`. On our Arc servers (and probably others) the himds executable is located at `/opt/azcmagent/bin/himds`. This failure requires manually setting the required env variables to bypass this statement or creating a symlink from /opt/azcmagent/bin to /var/opt/azcmagent/bin.

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/7db6c2ccdd121ad730517ebd5e6195feec06ed41/msal/managed_identity.py#L367

**Comment by rayluo** [comment]
Hi, @msalwen , I just noticed that your alias happens to have a prefix `msal` which is also the acronym MSAL of MicroSoft Authentication Library. :-)

Now we have a beta release with the bugfix for the issue you reported. Would you please install it by `pip install -i https://test.pypi.org/simple/ msal` and tell us whether it can solve the issue? Thanks!

**Comment by msalwen** [comment]
@rayluo I have checked the beta and it works as intended. Alignment bet my alias and package name is completely coincidental. Microsoft and I happen to share initials. 😄 

@jiasli I'm not sure whether you are involved with the Python packages supporting azure-cli as well as the base product, but not surprisingly, installing the msal beta alongside azure-cli-core raised a complaint from the latter about a version mismatch. I hope that a new release of azure-cli-core will follow the updated msal as soon as possible.

**Comment by jiasli** [comment]
Once MSAL releases a new version that includes https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/763. Azure CLI will adopt it in https://github.com/Azure/azure-cli/pull/30267.

**Comment by rayluo** [comment]
Released in MSAL Python 1.31.1
