### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by kannes** [AzureAD/microsoft-authentication-library-for-python#771]
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/60007ac58d94947287ba15be36e83ea1978b4cc1/msal/broker.py#L25C1-L25C90 points to https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/2406/files which is 404. Where can I find this information?

**Comment by rayluo** [comment]
You can't. In [the line right before the line you quoted](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.31.1/msal/broker.py#L24-L25), it already mentioned that the link is an "MSFT internal link".

That being said, I suppose what you are looking for is the info of "supported Windows versions". For that, you can find it in [public doc](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.__init__), quoted, "Windows 10+".
