### ISSUE TITLE
Clarify documentation for scopes

### ISSUE THREAD

**Issue by mattfeltonma** [AzureAD/microsoft-authentication-library-for-python#93]
Documentation located at [here](https://msal-python.readthedocs.io/en/latest/) states that scopes parameters is a list of strings.  Inserting multiple strings causes request for token to fail.  I don't believe multiple scopes are supported by the underlining API endpoints either based on [public documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)

Recommend documentation should clarify that while this can be a list of strings, the list can contain only one item.  This will resolve lack of clarity when there is a use case to obtain an access token usable across multiple scopes.  

Here is an example of how a list of strings with multiple items is parsed and passed in the underlining request **https://https://vault.azure.net/.default https://management.azure.com//.default**.  Instances where this problem could pop up would be solutions that are querying multiple resources across both the management and data plane and thus using different scopes.

**Comment by jmprieur** [comment]
@mattfeltonma : multiple scopes are supported, but they should all be for the same resource (audience). in your example you are asking a token for two audiences: vault.azure.net and management.azure.com.

When you want to access several resources, just call AcquireTokenSilent with the scopes for the second resource. 

We'll update the reference documentation. This behavior is documented in https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-user-gets-consent-for-multiple-resources for instance (this is for .NET, but applies to any languages)

**Comment by mattfeltonma** [comment]
Thank you so much for the clarification and correction!
