### ISSUE TITLE
After removing accounts, MS still logs me in automatically if I do not reopen the browser

### ISSUE THREAD

**Issue by 19hours** [AzureAD/microsoft-authentication-library-for-python#94]
I have a route that signs user out of their account. This works if the user closes their browser and opens it again. Microsoft will not prompt and automatically signs the user in if the user uses the same window to sign in.

```
@auth.route('/signout')
def sign_out():
  for account in msal_app.get_accounts():
    msal_app.remove_account(account)
  session.clear()
```

Do I need to clear anything else etc to sign the user out completely?

**Comment by 19hours** [comment]
Solved by logging out of Azure Directory.

**Comment by rayluo** [comment]
@19hours Glad that you figured it out by yourself. Yes those cookies in your browser would keep you signed in, if you don't manually log out from Azure Dictory. That part is outside the scope of MSAL Python library.

On a side note, based on your code snippet, you seem to use the `msal_app` as a global variable AND you seem to be utilizing MSAL's cache feature? We recommend to NOT use such combination. There will be [a new web sample demonstrating how to NOT share a `msal_app` instance between end users](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/2/files#diff-3f41e546893dc64b71aaacad12cad815). You can start to subscribe that sample repo (by click Watch button in github).

**Comment by 19hours** [comment]
@rayluo thanks I will take a look at it. Just curious what's wrong with one instance shared between users ?

**Comment by rayluo** [comment]
That is because an MSAL instance uses/maintains a token cache instance, currently in memory. When your web app potentially serves tons of users, that token cache would not scale well. So the recommended pattern is to use one cache per user (or per session), and feed that cache to a (new) MSAL instance for that session, as demonstrated in that sample.

We will actively explore more options in this area. And we will update that sample when new solution matures.

**Comment by seandenigris** [comment]
Logging out via https://login.microsoftonline.com/common/oauth2/v2.0/logout
 did not seem to work for me in my desktop app, where clearing web session data is not an option. Access tokens continued to work. I posted about it [on SO](https://stackoverflow.com/questions/74044735/msal-logging-out-via-python-desktop-app)
