### ISSUE TITLE
Username password sample doesn't work

### ISSUE THREAD

**Issue by palemium** [AzureAD/microsoft-authentication-library-for-python#96]
It looks like `acquire_token_by_username_password` method should belong to `ConfidentialClientApplication` class as this type of authorization requires client secret in the request.

I'm getting the following error replicating sample code:
```
{'error': 'invalid_client', 'error_description': "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: eacce55c-e487-4aee-8aa0-ee17775fa900\r\nCorrelation ID: 5076655f-dc98-4c33-8685-a9ad0113564f\r\nTimestamp: 2019-09-23 15:51:45Z", 'error_codes': [7000218], 'timestamp': '2019-09-23 15:51:45Z', 'trace_id': 'eacce55c-e487-4aee-8aa0-ee17775fa900', 'correlation_id': '5076655f-dc98-4c33-8685-a9ad0113564f', 'error_uri': 'https://login.microsoftonline.com/error?code=7000218'}
```

**Comment by jmprieur** [comment]
@palemium : the issue is that you need to say, in the application registration, that your application allows public client. See https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration#redirect-uris

**Comment by palemium** [comment]
@jmprieur Thank you
